import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {afterEach,beforeEach,expect,it} from 'vitest';
import {reconcileMigration} from '../src/crm-reconciliation';
import type {Env} from '../src/types';

let db:DatabaseSync,env:Env;const workspace='reconcile-workspace',now='2026-09-17T12:00:00.000Z',objects:string[]=[];
beforeEach(()=>{objects.length=0;db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(name=>name.endsWith('.sql')).sort())db.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const prepare=(sql:string)=>({bind(...values:unknown[]){const statement=db.prepare(sql);return{first:async()=>statement.get(...values as never[])??null,all:async()=>({results:statement.all(...values as never[])}),run:async()=>({success:true,meta:statement.run(...values as never[])})};}});env={CRM_DB:{prepare},STORAGE:{head:async(key:string)=>objects.includes(key)?{}:null,put:async(key:string)=>{objects.push(key);return{};}}} as unknown as Env;db.prepare('INSERT INTO workspaces VALUES (?,?,?)').run(workspace,'Reconcile',now);});afterEach(()=>db.close());
it('persists a passing count, relationship, and R2 reconciliation report',async()=>{db.prepare('INSERT INTO contacts (id,workspace_id,first_name,last_name,created_at,updated_at) VALUES (?,?,?,?,?,?)').run('person',workspace,'Ada','Lovelace',now,now);const report=await reconcileMigration(env,workspace,'a'.repeat(64),{contact:1});expect(report).toMatchObject({status:'passed',relationshipErrors:0,missingR2Objects:0,countMismatches:0});expect(db.prepare('SELECT status FROM migration_reconciliations').get()).toEqual({status:'passed'});expect(objects[0]).toMatch(/^reconciliations\//);});

it('fails reconciliation for dangling relationships and missing R2 objects',async()=>{db.exec('PRAGMA foreign_keys=OFF');db.prepare('INSERT INTO record_relationships VALUES (?,?,?,?,?,?,?,?)').run('rel',workspace,'contact','missing','company','missing','related',now);db.prepare('INSERT INTO crm_files VALUES (?,?,?,?,?,?,?)').run('file',workspace,`crm/${workspace}/missing.bin`,'missing.bin','application/octet-stream',1,now);const report=await reconcileMigration(env,workspace,'b'.repeat(64),{file:1,relationship:1});expect(report.status).toBe('failed');expect(report.relationshipErrors).toBeGreaterThan(0);expect(report.missingR2Objects).toBe(1);});
