import {createHash} from 'node:crypto';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterEach,expect,it} from 'vitest';
import {reconcilePostgresExport} from '../scripts/reconcile-postgres-export.mjs';

const dirs:string[]=[];afterEach(()=>{for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});
it('verifies source checksums and emits dependency-ordered canonical artifacts',async()=>{const root=mkdtempSync(join(tmpdir(),'twenty-reconcile-')),output=join(root,'output'),workspaceId='00000000-0000-4000-8000-000000000001';dirs.push(root);mkdirSync(output);const person='{"scope":"workspace","schema":"workspace_a","table":"person","row":{"id":"person-one","nameFirstName":"Ada","nameLastName":"Lovelace"}}\n',unknown='{"scope":"workspace","schema":"workspace_a","table":"widget","row":{"id":"widget-one","title":"Legacy"}}\n';writeFileSync(join(root,'person.ndjson'),person);writeFileSync(join(root,'widget.ndjson'),unknown);const sha=(value:string)=>createHash('sha256').update(value).digest('hex');writeFileSync(join(root,'manifest.json'),JSON.stringify({workspaceId,startedAt:'2026-01-01T00:00:00.000Z',completedAt:'2026-01-01T01:00:00.000Z',totals:{rows:2},tables:[{table:'person',file:'person.ndjson',rows:1,sha256:sha(person)},{table:'widget',file:'widget.ndjson',rows:1,sha256:sha(unknown)}]}));const result=await reconcilePostgresExport({extract:root,output,workspaceId});expect(result.counts).toMatchObject({contact:1,customObject:1,customRecord:1});expect(result.files.map((file:any)=>file.objectType)).toEqual(['contact','customObject','customRecord']);expect(readFileSync(join(output,'01-contact.ndjson'),'utf8')).toContain('"firstName":"Ada"');expect(JSON.parse(readFileSync(join(output,'reconciliation.json'),'utf8')).sourceRows).toBe(2);});

it('rejects a modified PostgreSQL extraction artifact',async()=>{const root=mkdtempSync(join(tmpdir(),'twenty-reconcile-bad-')),workspaceId='00000000-0000-4000-8000-000000000001';dirs.push(root);writeFileSync(join(root,'person.ndjson'),'tampered\n');writeFileSync(join(root,'manifest.json'),JSON.stringify({workspaceId,totals:{rows:1},tables:[{table:'person',file:'person.ndjson',rows:1,sha256:'0'.repeat(64)}]}));await expect(reconcilePostgresExport({extract:root,output:join(root,'out'),workspaceId})).rejects.toThrow('checksum mismatch');});
