import { DatabaseSync } from 'node:sqlite';
import { readFileSync,readdirSync } from 'node:fs';
import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { handleProviderIntegrationApi } from '../src/provider-integrations';
import type { Env } from '../src/types';

const workspace='provider-workspace',userId='11111111-1111-4111-8111-111111111111',subject=`user:${userId}`,session='provider-session',now='2026-09-17T00:00:00.000Z';
let db:DatabaseSync;let env:Env;
beforeEach(()=>{db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(name=>name.endsWith('.sql')).sort())db.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const prepare=(sql:string)=>({bind:(...values:unknown[])=>{const statement=db.prepare(sql);return{first:async()=>statement.get(...values as never[])??null,all:async()=>({results:statement.all(...values as never[])}),run:async()=>({success:true,meta:statement.run(...values as never[])})};}});env={ACCESS_REQUIRED:'true',SERVER_URL:'https://crm.example.test',GOOGLE_OAUTH_CLIENT_ID:'google-client',GOOGLE_OAUTH_CLIENT_SECRET:'google-secret',INTEGRATION_ENCRYPTION_KEY:btoa(String.fromCharCode(...new Uint8Array(32).fill(7))),CRM_DB:{prepare,batch:async(statements:{run:()=>Promise<unknown>}[])=>{db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}}} as unknown as Env;db.prepare('INSERT INTO workspaces VALUES (?,?,?)').run(workspace,'Provider',now);db.prepare('INSERT INTO native_users (id,email,password_hash,password_salt,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(userId,'owner@example.test','x','x',now,now);db.prepare("INSERT INTO workspace_members VALUES (?,?,'owner','active',?)").run(workspace,subject,now);db.prepare('INSERT INTO native_sessions VALUES (?,?,?,?,?,?,NULL)').run(session,workspace,subject,now,now,'2099-01-01T00:00:00.000Z');});
afterEach(()=>{vi.unstubAllGlobals();db.close();});
const request=(path:string,method='GET')=>new Request(`https://crm.example.test${path}`,{method,headers:{cookie:`twenty_session=${session}`,'x-workspace-id':workspace}});

it('uses PKCE, one-time state, real provider validation, and encrypted credential storage',async()=>{
  const started=(await handleProviderIntegrationApi(request('/api/integrations/oauth/google/start','POST'),env))!;expect(started.status).toBe(200);const startBody=await started.json() as any;const authorization=new URL(startBody.data.authorizationUrl);expect(authorization.searchParams.get('code_challenge_method')).toBe('S256');expect(authorization.searchParams.get('client_secret')).toBeNull();const state=authorization.searchParams.get('state')!;
  const storedState=db.prepare('SELECT encrypted_verifier,verifier_iv,consumed_at FROM provider_oauth_states').get() as any;expect(storedState.encrypted_verifier).not.toContain('google-secret');expect(storedState.consumed_at).toBeNull();
  const providerFetch=vi.fn().mockResolvedValueOnce(Response.json({access_token:'access-value',refresh_token:'refresh-value',expires_in:3600,scope:'openid email'})).mockResolvedValueOnce(Response.json({email:'verified@example.test',name:'Verified User'}));vi.stubGlobal('fetch',providerFetch);
  const callback=(await handleProviderIntegrationApi(request(`/api/integrations/oauth/google/callback?state=${encodeURIComponent(state)}&code=provider-code`),env))!;expect(callback.status).toBe(303);expect(callback.headers.get('location')).toContain('providerConnected=google');expect(providerFetch).toHaveBeenCalledTimes(2);
  const account=db.prepare('SELECT account_type,status,config_json FROM integration_accounts').get();expect(account).toEqual({account_type:'google',status:'connected',config_json:'{}'});const credential=db.prepare('SELECT encrypted_tokens,token_iv FROM integration_credentials').get() as any;expect(credential.encrypted_tokens).not.toContain('access-value');expect(credential.encrypted_tokens).not.toContain('refresh-value');
  expect(db.prepare("SELECT action,object_type FROM crm_audit_events WHERE workspace_id=?").get(workspace)).toEqual({action:'connect',object_type:'integration_account'});
  const replay=(await handleProviderIntegrationApi(request(`/api/integrations/oauth/google/callback?state=${encodeURIComponent(state)}&code=provider-code`),env))!;expect(replay.status).toBe(400);
});

it('denies provider configuration to standard members',async()=>{db.prepare("UPDATE workspace_members SET role='member' WHERE workspace_id=? AND identity_subject=?").run(workspace,subject);const response=(await handleProviderIntegrationApi(request('/api/integrations/oauth/google/start','POST'),env))!;expect(response.status).toBe(403);expect(db.prepare('SELECT COUNT(*) AS count FROM provider_oauth_states').get()).toEqual({count:0});});

it('rejects cross-origin provider mutations before changing state',async()=>{const response=(await handleProviderIntegrationApi(new Request('https://crm.example.test/api/integrations/oauth/google/start',{method:'POST',headers:{cookie:`twenty_session=${session}`,'x-workspace-id':workspace,origin:'https://attacker.example'}}),env))!;expect(response.status).toBe(403);expect(db.prepare('SELECT COUNT(*) AS count FROM provider_oauth_states').get()).toEqual({count:0});});

it('binds OAuth callbacks to the hostname that owns the initiating session',async()=>{const started=(await handleProviderIntegrationApi(request('/api/integrations/oauth/google/start','POST'),env))!;const authorization=new URL((await started.json() as any).data.authorizationUrl);const state=authorization.searchParams.get('state')!;expect(authorization.searchParams.get('redirect_uri')).toBe('https://crm.example.test/api/integrations/oauth/google/callback');const mismatched=(await handleProviderIntegrationApi(new Request(`https://other.example.test/api/integrations/oauth/google/callback?state=${encodeURIComponent(state)}&code=provider-code`,{headers:{cookie:`twenty_session=${session}`,'x-workspace-id':workspace}}),env))!;expect(mismatched.status).toBe(403);expect(db.prepare('SELECT consumed_at FROM provider_oauth_states').get()).toEqual({consumed_at:null});});
