import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {handleD1Crm} from '../src/d1-crm';
import {writeCrmExport} from '../src/crm-export';
import type {Env} from '../src/types';

let db:DatabaseSync;let env:Env;let objects:Map<string,string>;const workspace='transfer-workspace',now='2026-09-17T12:00:00.000Z';
beforeEach(()=>{db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(name=>name.endsWith('.sql')).sort())db.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const prepare=(sql:string)=>({bind(...values:unknown[]){const statement=db.prepare(sql);return{first:async()=>statement.get(...values as never[])??null,all:async()=>({results:statement.all(...values as never[])}),run:async()=>({success:true,meta:statement.run(...values as never[])})};}});objects=new Map();env={OPS_TOKEN:'ops',CRM_DB:{prepare,batch:async(statements:{run:()=>Promise<unknown>}[])=>Promise.all(statements.map(statement=>statement.run()))},CRM_EXPORT_WF:{create:vi.fn().mockImplementation(async()=>({id:crypto.randomUUID()}))},STORAGE:{put:async(key:string,value:unknown)=>{objects.set(key,typeof value==='string'?value:await new Response(value as BodyInit).text());return{};},get:async(key:string)=>objects.has(key)?{body:objects.get(key)}:null}} as unknown as Env;db.prepare('INSERT INTO workspaces VALUES (?,?,?)').run(workspace,'Transfers',now);db.prepare("INSERT INTO workspace_members VALUES (?,'legacy-ops-token','owner','active',?)").run(workspace,now);});
afterEach(()=>db.close());
async function call(path:string,method='GET',body?:unknown){const response=(await handleD1Crm(new Request(`https://crm.test${path}`,{method,headers:{'content-type':'application/json','x-workspace-id':workspace},body:body===undefined?undefined:JSON.stringify(body)}),env))!;return{response,body:response.headers.get('content-type')?.includes('json')?await response.clone().json() as Record<string,any>:null};}

it('persists import progress, error artifacts, cancellation, and explicit resume',async()=>{const started=await call('/api/crm/import','POST',{runId:'import-1',objectType:'contact',cursor:'batch-1',total:2,mapping:{First:'firstName'},records:[{firstName:'Ada',lastName:'Lovelace'},{firstName:'Missing last'}]});expect(started.response.status).toBe(200);expect(started.body?.data).toMatchObject({runId:'import-1',processed:1,failed:1,cursor:'batch-1'});const status=await call('/api/crm/import/import-1');expect(status.body?.data).toMatchObject({status:'running',processed:1,failed:1,total:2});const errors=await call('/api/crm/import/import-1/errors');expect(errors.response.status).toBe(200);expect(await errors.response.json()).toMatchObject({runId:'import-1',errors:[{index:1}]});expect((await call('/api/crm/import/import-1/cancel','POST')).body?.data.status).toBe('cancelled');expect((await call('/api/crm/import','POST',{runId:'import-1',objectType:'contact',records:[]})).response.status).toBe(409);expect((await call('/api/crm/import/import-1/resume','POST')).body?.data).toMatchObject({status:'pending',cursor:'batch-1'});});

it('cancels and resumes durable exports and authorizes the download',async()=>{const started=await call('/api/crm/export','POST',{objectType:'company'});expect(started.response.status).toBe(202);const id=started.body?.data.id as string;expect((await call(`/api/crm/exports/${id}/cancel`,'POST')).body?.data.status).toBe('cancelled');const resumed=await call(`/api/crm/exports/${id}/resume`,'POST');expect(resumed.response.status).toBe(202);expect(resumed.body?.data.status).toBe('queued');const key=`exports/${workspace}/${id}.json`;objects.set(key,'{"ok":true}');db.prepare("UPDATE crm_exports SET status='complete',object_key=?,bytes=11 WHERE id=?").run(key,id);const download=await call(`/api/crm/exports/${id}/download`);expect(download.response.status).toBe(200);expect(await download.response.text()).toBe('{"ok":true}');});

it('exports every supported CRM family through paginated multipart NDJSON',async()=>{
  const exportId='export-all',parts:Uint8Array[]=[];db.prepare("INSERT INTO crm_exports (id,workspace_id,workflow_id,object_type,status,created_at,updated_at) VALUES (?,?,?,'all','running',?,?)").run(exportId,workspace,'workflow-all',now,now);
  const insert=db.prepare("INSERT INTO contacts (id,workspace_id,first_name,last_name,created_at,updated_at) VALUES (?,?,?,?,?,?)");for(let index=0;index<501;index++)insert.run(`contact-${String(index).padStart(3,'0')}`,workspace,'Person',String(index),now,now);
  db.prepare("INSERT INTO crm_tasks (id,workspace_id,title,status,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,'TODO','tester','tester',?,?)").run('task-export',workspace,'Review export',now,now);
  db.prepare('INSERT INTO custom_objects (id,workspace_id,object_key,label,plural_label,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run('custom-object',workspace,'petition','Petition','Petitions',now,now);
  db.prepare('INSERT INTO custom_records (id,workspace_id,object_key,data_json,created_at,updated_at) VALUES (?,?,?,?,?,?)').run('custom-record',workspace,'petition','{"title":"One"}',now,now);
  env.STORAGE={createMultipartUpload:async()=>({uploadId:'upload',key:'key',uploadPart:async(partNumber:number,value:Uint8Array)=>{parts.push(value);return{partNumber,etag:`etag-${partNumber}`};},complete:async()=>({}),abort:async()=>undefined})} as unknown as R2Bucket;
  const result=await writeCrmExport(env,{workspaceId:workspace,objectType:'all',exportId});expect(result.records).toBeGreaterThanOrEqual(504);expect(result.key).toBe(`exports/${workspace}/${exportId}.ndjson`);
  const text=new TextDecoder().decode(Buffer.concat(parts.map(part=>Buffer.from(part))));const lines=text.trim().split('\n').map(line=>JSON.parse(line));
  expect(lines[0]).toMatchObject({kind:'manifest',schemaVersion:2,objectType:'all'});expect(lines.some(line=>line.objectType==='task'&&line.record.id==='task-export')).toBe(true);expect(lines.some(line=>line.objectType==='customRecord'&&line.record.id==='custom-record')).toBe(true);expect(lines.at(-1)).toMatchObject({kind:'summary',records:result.records});
});
