import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {afterEach,beforeEach,expect,it} from 'vitest';
import {handleRegisteredWebhookReceiver,handleWebhookSelfTest} from '../src/webhook-receiver';
import {executeWebhookDelivery} from '../src/outbound-webhooks';
import type {Env} from '../src/types';

let db:DatabaseSync,env:Env;const workspace='webhook-workspace',secret='outbound-test-secret',apiToken=`twenty_${'a'.repeat(32)}`,now='2026-09-17T12:00:00.000Z',jobs:unknown[]=[];
const sign=async(timestamp:string,body:string)=>{const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return[...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}:${body}`)))].map(byte=>byte.toString(16).padStart(2,'0')).join('');};
beforeEach(async()=>{jobs.length=0;db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(name=>name.endsWith('.sql')).sort())db.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));const prepare=(sql:string)=>({bind(...values:unknown[]){const statement=db.prepare(sql);return{first:async()=>statement.get(...values as never[])??null,all:async()=>({results:statement.all(...values as never[])}),run:async()=>({success:true,meta:statement.run(...values as never[])})};}});env={CRM_DB:{prepare},JOBS_QUEUE:{send:async(job:unknown)=>{jobs.push(job);}},SERVER_URL:'https://twenty.example.test',ACCESS_REQUIRED:'true',WEBHOOK_TOKEN:'sender-secret',OUTBOUND_WEBHOOK_SECRET:secret,WEBHOOK_ALLOWED_HOSTS:'twenty.example.test'} as unknown as Env;db.prepare('INSERT INTO workspaces VALUES (?,?,?)').run(workspace,'Webhook',now);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(apiToken)),hash=[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');db.prepare('INSERT INTO native_api_keys (id,workspace_id,name,token_hash,role,created_at) VALUES (?,?,?,?,?,?)').run('key',workspace,'test',hash,'admin',now);});
afterEach(()=>db.close());

it('registers an exact-host receiver and completes its signed queue loopback',async()=>{const response=await handleWebhookSelfTest(new Request('https://twenty.example.test/_ops/webhooks/self-test',{method:'POST',headers:{authorization:`Bearer ${apiToken}`,'content-type':'application/json'},body:JSON.stringify({workspaceId:workspace})}),env);expect(response.status).toBe(202);expect(db.prepare('SELECT url,active FROM native_webhooks').get()).toEqual({url:'https://twenty.example.test/webhooks/receiver',active:1});expect(db.prepare('SELECT status FROM webhook_deliveries').get()).toEqual({status:'queued'});expect(jobs).toHaveLength(1);expect((await executeWebhookDelivery(jobs[0] as never,env)).status).toBe(204);expect(db.prepare('SELECT status,response_status FROM webhook_deliveries').get()).toEqual({status:'delivered',response_status:202});expect(db.prepare('SELECT COUNT(*) AS count FROM webhook_receiver_events').get()).toEqual({count:1});});

it('accepts only current valid outbound signatures and deduplicates receipts',async()=>{const body=JSON.stringify({id:'event-one',event:'webhook.self-test',workspaceId:workspace,data:{ok:true}}),timestamp=String(Date.now()),signature=await sign(timestamp,body),request=()=>new Request('https://twenty.example.test/webhooks/receiver',{method:'POST',headers:{'content-type':'application/json','x-twenty-webhook-timestamp':timestamp,'x-twenty-webhook-signature':signature},body});expect((await handleRegisteredWebhookReceiver(request(),env)).status).toBe(202);expect((await handleRegisteredWebhookReceiver(request(),env)).status).toBe(202);expect(db.prepare('SELECT COUNT(*) AS count FROM webhook_receiver_events').get()).toEqual({count:1});const bad=new Request('https://twenty.example.test/webhooks/receiver',{method:'POST',headers:{'x-twenty-webhook-timestamp':timestamp,'x-twenty-webhook-signature':'0'.repeat(64)},body});expect((await handleRegisteredWebhookReceiver(bad,env)).status).toBe(401);});
