import type { Env } from './types';

export interface CrmImportParams { workspaceId:string; importId:string }
export const CRM_IMPORT_TYPES=['contact','company','pipeline','opportunity','activity','file','task','taskTarget','note','noteTarget','attachment','relationship','customObject','customField','customRecord','view','fileLink'] as const;
export type CrmImportType=typeof CRM_IMPORT_TYPES[number];
export type ImportMapping=Record<string,string>;

const CHUNK_BYTES=512*1024,MAX_RECORD_BYTES=1024*1024,MAX_RECORDS_PER_STEP=100;
const validId=(v:unknown):v is string=>typeof v==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(v);
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const value=(raw:Record<string,unknown>,...keys:string[])=>{for(const key of keys)if(raw[key]!==undefined)return raw[key];};
const text=(raw:Record<string,unknown>,keys:string[],max:number,required=false)=>{const found=value(raw,...keys);if(found==null&&!required)return null;if(typeof found!=='string'||required&&!found.trim())throw new Error(`${keys[0]}${required?' is required':' must be text'}`);return found.slice(0,max);};
const time=(raw:Record<string,unknown>,keys:string[],fallback:string|null)=>{const found=value(raw,...keys);if(found==null)return fallback;if(typeof found!=='string'||Number.isNaN(Date.parse(found)))throw new Error(`${keys[0]} must be an ISO timestamp`);return found;};
const integer=(raw:Record<string,unknown>,keys:string[])=>{const found=value(raw,...keys);if(found==null)return null;if(typeof found!=='number'||!Number.isSafeInteger(found))throw new Error(`${keys[0]} must be an integer`);return found;};
const numeric=(raw:Record<string,unknown>,keys:string[],fallback=0)=>{const found=value(raw,...keys);if(found==null)return fallback;if(typeof found!=='number'||!Number.isFinite(found))throw new Error(`${keys[0]} must be a number`);return found;};
const json=(raw:Record<string,unknown>,keys:string[],fallback:unknown)=>{const found=value(raw,...keys);if(found==null)return JSON.stringify(fallback);if(typeof found==='string'){try{JSON.parse(found);return found;}catch{throw new Error(`${keys[0]} must contain valid JSON`);}}return JSON.stringify(found);};
const ref=(raw:Record<string,unknown>,keys:string[],required=false)=>{const found=value(raw,...keys);if(found==null&&!required)return null;if(!validId(found))throw new Error(`${keys[0]} must be a valid identifier`);return found;};
const bit=(raw:Record<string,unknown>,keys:string[],fallback:boolean)=>{const found=value(raw,...keys);if(found==null)return fallback?1:0;if(typeof found==='boolean')return found?1:0;if(found===0||found===1)return found;throw new Error(`${keys[0]} must be boolean`);};

const fields:Record<CrmImportType,string[]>={
  contact:['id','firstName','lastName','email','customFields','createdAt','updatedAt','deletedAt'],company:['id','name','domain','customFields','createdAt','updatedAt','deletedAt'],pipeline:['id','name','createdAt'],
  opportunity:['id','name','amountCents','stage','companyId','pointOfContactId','pipelineId','customFields','createdAt','updatedAt','deletedAt'],activity:['id','type','title','body','contactId','companyId','opportunityId','dueAt','completedAt','customFields','createdAt','updatedAt','deletedAt'],
  file:['id','objectKey','filename','contentType','bytes','createdAt'],task:['id','position','title','bodyV2','dueAt','status','assigneeSubject','createdBy','updatedBy','createdAt','updatedAt','deletedAt'],taskTarget:['id','taskId','targetType','targetId','createdAt','updatedAt','deletedAt'],
  note:['id','position','title','bodyV2','createdBy','updatedBy','createdAt','updatedAt','deletedAt'],noteTarget:['id','noteId','targetType','targetId','createdAt','updatedAt','deletedAt'],attachment:['id','fileId','name','targetType','targetId','createdBy','createdAt','updatedAt','deletedAt'],
  relationship:['id','sourceType','sourceId','targetType','targetId','relationKey','createdAt'],customObject:['id','objectKey','label','pluralLabel','createdAt','updatedAt'],customField:['id','objectType','fieldKey','label','fieldType','options','settings','isNullable','isUnique','createdAt'],
  customRecord:['id','objectKey','data','createdAt','updatedAt','deletedAt'],view:['id','objectType','name','filters','sort','createdAt','updatedAt'],fileLink:['fileId','recordType','recordId','createdAt'],
};

export const isCrmImportType=(v:unknown):v is CrmImportType=>typeof v==='string'&&(CRM_IMPORT_TYPES as readonly string[]).includes(v);
export const importFields=(type:CrmImportType)=>fields[type];
export function mapImportRecord(type:CrmImportType,raw:Record<string,unknown>,mapping:ImportMapping={}):Record<string,unknown>{const allowed=new Set(fields[type]),mapped={...raw};for(const[source,target]of Object.entries(mapping)){if(!allowed.has(target))throw new Error(`unsupported mapped field ${target}`);if(Object.prototype.hasOwnProperty.call(raw,source))mapped[target]=raw[source];}return mapped;}

async function ensureChange(result:D1Result<unknown>,env:Env,workspaceId:string,table:string,id:string){if(Number(result.meta?.changes??0)>0)return;const row=await env.CRM_DB!.prepare(`SELECT workspace_id as workspaceId FROM ${table} WHERE id=?`).bind(id).first<{workspaceId:string}>();if(row?.workspaceId!==workspaceId)throw new Error('record ID belongs to another workspace');}
async function requireTenantRow(env:Env,workspaceId:string,table:string,id:string|null,label:string){if(!id)return;const found=await env.CRM_DB!.prepare(`SELECT 1 FROM ${table} WHERE workspace_id=? AND id=?`).bind(workspaceId,id).first();if(!found)throw new Error(`${label} is not available in this workspace`);}
async function requireTarget(env:Env,workspaceId:string,type:string,id:string){const table=({person:'contacts',contact:'contacts',company:'companies',opportunity:'opportunities',activity:'activities',task:'crm_tasks',note:'crm_notes',pipeline:'pipelines'} as Record<string,string>)[type];if(table)return requireTenantRow(env,workspaceId,table,id,'target');const objectKey=type.startsWith('custom:')?type.slice(7):type;if(!/^[a-z][a-z0-9_]{0,63}$/.test(objectKey))throw new Error('unsupported target type');const found=await env.CRM_DB!.prepare('SELECT 1 FROM custom_records WHERE workspace_id=? AND object_key=? AND id=?').bind(workspaceId,objectKey,id).first();if(!found)throw new Error('target is not available in this workspace');}

export async function writeImportRecord(env:Env,workspaceId:string,type:CrmImportType,raw:Record<string,unknown>,now=new Date().toISOString()):Promise<string>{
  const id=type==='fileLink'?'':validId(raw.id)?raw.id:crypto.randomUUID(),created=time(raw,['createdAt','created_at'],now)!,updated=time(raw,['updatedAt','updated_at'],now)!;let result:D1Result<unknown>;
  if(type==='contact'){result=await env.CRM_DB!.prepare("INSERT INTO contacts (id,workspace_id,first_name,last_name,email,custom_fields_json,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,email=excluded.email,custom_fields_json=excluded.custom_fields_json,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE contacts.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['firstName','first_name'],120,true),text(raw,['lastName','last_name'],120,true),text(raw,['email'],254),json(raw,['customFields','custom_fields_json'],{}),created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'contacts',id);return id;}
  if(type==='company'){result=await env.CRM_DB!.prepare("INSERT INTO companies (id,workspace_id,name,domain,custom_fields_json,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,domain=excluded.domain,custom_fields_json=excluded.custom_fields_json,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE companies.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['name'],200,true),text(raw,['domain'],254),json(raw,['customFields','custom_fields_json'],{}),created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'companies',id);return id;}
  if(type==='pipeline'){result=await env.CRM_DB!.prepare("INSERT INTO pipelines (id,workspace_id,name,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name WHERE pipelines.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['name'],200,true),created).run();await ensureChange(result,env,workspaceId,'pipelines',id);return id;}
  if(type==='opportunity'){const company=ref(raw,['companyId','company_id']),contact=ref(raw,['pointOfContactId','point_of_contact_id']),pipeline=ref(raw,['pipelineId','pipeline_id']);await requireTenantRow(env,workspaceId,'companies',company,'company');await requireTenantRow(env,workspaceId,'contacts',contact,'point of contact');await requireTenantRow(env,workspaceId,'pipelines',pipeline,'pipeline');result=await env.CRM_DB!.prepare("INSERT INTO opportunities (id,workspace_id,name,amount_cents,stage,company_id,point_of_contact_id,pipeline_id,custom_fields_json,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,amount_cents=excluded.amount_cents,stage=excluded.stage,company_id=excluded.company_id,point_of_contact_id=excluded.point_of_contact_id,pipeline_id=excluded.pipeline_id,custom_fields_json=excluded.custom_fields_json,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE opportunities.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['name'],200,true),integer(raw,['amountCents','amount_cents']),text(raw,['stage'],80)??'prospecting',company,contact,pipeline,json(raw,['customFields','custom_fields_json'],{}),created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'opportunities',id);return id;}
  if(type==='activity'){const kind=text(raw,['type'],20,true)!;if(!['note','task','call','email'].includes(kind))throw new Error('type must be note, task, call, or email');const contact=ref(raw,['contactId','contact_id']),company=ref(raw,['companyId','company_id']),opportunity=ref(raw,['opportunityId','opportunity_id']);await requireTenantRow(env,workspaceId,'contacts',contact,'contact');await requireTenantRow(env,workspaceId,'companies',company,'company');await requireTenantRow(env,workspaceId,'opportunities',opportunity,'opportunity');result=await env.CRM_DB!.prepare("INSERT INTO activities (id,workspace_id,type,title,body,contact_id,company_id,opportunity_id,due_at,completed_at,created_at,updated_at,deleted_at,custom_fields_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET type=excluded.type,title=excluded.title,body=excluded.body,contact_id=excluded.contact_id,company_id=excluded.company_id,opportunity_id=excluded.opportunity_id,due_at=excluded.due_at,completed_at=excluded.completed_at,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at,custom_fields_json=excluded.custom_fields_json WHERE activities.workspace_id=excluded.workspace_id").bind(id,workspaceId,kind,text(raw,['title'],500,true),text(raw,['body'],20000),contact,company,opportunity,time(raw,['dueAt','due_at'],null),time(raw,['completedAt','completed_at'],null),created,updated,time(raw,['deletedAt','deleted_at'],null),json(raw,['customFields','custom_fields_json'],{})).run();await ensureChange(result,env,workspaceId,'activities',id);return id;}
  if(type==='file'){const key=text(raw,['objectKey','object_key'],1024,true)!;if(!key.startsWith(`crm/${workspaceId}/`)&&!key.startsWith(`migrations/${workspaceId}/`))throw new Error('objectKey must be tenant scoped');if(!await env.STORAGE.head(key))throw new Error('R2 object is missing');result=await env.CRM_DB!.prepare("INSERT INTO crm_files (id,workspace_id,object_key,filename,content_type,bytes,created_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key,filename=excluded.filename,content_type=excluded.content_type,bytes=excluded.bytes WHERE crm_files.workspace_id=excluded.workspace_id").bind(id,workspaceId,key,text(raw,['filename'],255,true),text(raw,['contentType','content_type'],255,true),integer(raw,['bytes'])??0,created).run();await ensureChange(result,env,workspaceId,'crm_files',id);return id;}
  if(type==='task'){const status=text(raw,['status'],20)??'TODO';if(!['TODO','DONE'].includes(status))throw new Error('status must be TODO or DONE');const creator=text(raw,['createdBy','created_by'],254,true)!;result=await env.CRM_DB!.prepare("INSERT INTO crm_tasks (id,workspace_id,position,title,body_v2_json,due_at,status,assignee_subject,created_by,updated_by,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET position=excluded.position,title=excluded.title,body_v2_json=excluded.body_v2_json,due_at=excluded.due_at,status=excluded.status,assignee_subject=excluded.assignee_subject,updated_by=excluded.updated_by,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE crm_tasks.workspace_id=excluded.workspace_id").bind(id,workspaceId,numeric(raw,['position']),text(raw,['title'],500),json(raw,['bodyV2','body_v2_json'],null),time(raw,['dueAt','due_at'],null),status,text(raw,['assigneeSubject','assignee_subject'],254),creator,text(raw,['updatedBy','updated_by'],254)??creator,created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'crm_tasks',id);return id;}
  if(type==='note'){const creator=text(raw,['createdBy','created_by'],254,true)!;result=await env.CRM_DB!.prepare("INSERT INTO crm_notes (id,workspace_id,position,title,body_v2_json,created_by,updated_by,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET position=excluded.position,title=excluded.title,body_v2_json=excluded.body_v2_json,updated_by=excluded.updated_by,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE crm_notes.workspace_id=excluded.workspace_id").bind(id,workspaceId,numeric(raw,['position']),text(raw,['title'],500)??'',json(raw,['bodyV2','body_v2_json'],null),creator,text(raw,['updatedBy','updated_by'],254)??creator,created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'crm_notes',id);return id;}
  if(type==='taskTarget'||type==='noteTarget'){const kind=type==='taskTarget'?'task':'note',table=`crm_${kind}_targets`,parent=`${kind}_id`,parentId=ref(raw,[`${kind}Id`,parent],true)!,targetType=text(raw,['targetType','target_type'],80,true)!,targetId=ref(raw,['targetId','target_id'],true)!;await requireTenantRow(env,workspaceId,kind==='task'?'crm_tasks':'crm_notes',parentId,kind);await requireTarget(env,workspaceId,targetType,targetId);result=await env.CRM_DB!.prepare(`INSERT INTO ${table} (id,workspace_id,${parent},target_type,target_id,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET ${parent}=excluded.${parent},target_type=excluded.target_type,target_id=excluded.target_id,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE ${table}.workspace_id=excluded.workspace_id`).bind(id,workspaceId,parentId,targetType,targetId,created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,table,id);return id;}
  if(type==='attachment'){const target=text(raw,['targetType','target_type'],30,true)!,targetId=ref(raw,['targetId','target_id'],true)!,fileId=ref(raw,['fileId','file_id'],true)!;if(!['person','company','opportunity','activity','task','note'].includes(target))throw new Error('invalid attachment targetType');await requireTenantRow(env,workspaceId,'crm_files',fileId,'file');await requireTarget(env,workspaceId,target,targetId);result=await env.CRM_DB!.prepare("INSERT INTO crm_attachments (id,workspace_id,file_id,name,target_type,target_id,created_by,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET file_id=excluded.file_id,name=excluded.name,target_type=excluded.target_type,target_id=excluded.target_id,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE crm_attachments.workspace_id=excluded.workspace_id").bind(id,workspaceId,fileId,text(raw,['name'],255,true),target,targetId,text(raw,['createdBy','created_by'],254,true),created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'crm_attachments',id);return id;}
  if(type==='relationship'){const sourceType=text(raw,['sourceType','source_type'],80,true)!,sourceId=ref(raw,['sourceId','source_id'],true)!,targetType=text(raw,['targetType','target_type'],80,true)!,targetId=ref(raw,['targetId','target_id'],true)!;await requireTarget(env,workspaceId,sourceType,sourceId);await requireTarget(env,workspaceId,targetType,targetId);result=await env.CRM_DB!.prepare("INSERT INTO record_relationships (id,workspace_id,source_type,source_id,target_type,target_id,relation_key,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET source_type=excluded.source_type,source_id=excluded.source_id,target_type=excluded.target_type,target_id=excluded.target_id,relation_key=excluded.relation_key WHERE record_relationships.workspace_id=excluded.workspace_id").bind(id,workspaceId,sourceType,sourceId,targetType,targetId,text(raw,['relationKey','relation_key'],120,true),created).run();await ensureChange(result,env,workspaceId,'record_relationships',id);return id;}
  if(type==='customObject'){result=await env.CRM_DB!.prepare("INSERT INTO custom_objects (id,workspace_id,object_key,label,plural_label,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key,label=excluded.label,plural_label=excluded.plural_label,updated_at=excluded.updated_at WHERE custom_objects.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['objectKey','object_key'],64,true),text(raw,['label'],120,true),text(raw,['pluralLabel','plural_label'],120,true),created,updated).run();await ensureChange(result,env,workspaceId,'custom_objects',id);return id;}
  if(type==='customField'){result=await env.CRM_DB!.prepare("INSERT INTO custom_fields (id,workspace_id,object_type,field_key,label,field_type,options_json,settings_json,is_nullable,is_unique,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_type=excluded.object_type,field_key=excluded.field_key,label=excluded.label,field_type=excluded.field_type,options_json=excluded.options_json,settings_json=excluded.settings_json,is_nullable=excluded.is_nullable,is_unique=excluded.is_unique WHERE custom_fields.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['objectType','object_type'],128,true),text(raw,['fieldKey','field_key'],128,true),text(raw,['label'],120,true),text(raw,['fieldType','field_type'],30,true),json(raw,['options','options_json'],null),json(raw,['settings','settings_json'],null),bit(raw,['isNullable','is_nullable'],true),bit(raw,['isUnique','is_unique'],false),created).run();await ensureChange(result,env,workspaceId,'custom_fields',id);return id;}
  if(type==='customRecord'){result=await env.CRM_DB!.prepare("INSERT INTO custom_records (id,workspace_id,object_key,data_json,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key,data_json=excluded.data_json,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at WHERE custom_records.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['objectKey','object_key'],64,true),json(raw,['data','data_json'],{}),created,updated,time(raw,['deletedAt','deleted_at'],null)).run();await ensureChange(result,env,workspaceId,'custom_records',id);return id;}
  if(type==='view'){result=await env.CRM_DB!.prepare("INSERT INTO saved_views (id,workspace_id,object_type,name,filters_json,sort_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_type=excluded.object_type,name=excluded.name,filters_json=excluded.filters_json,sort_json=excluded.sort_json,updated_at=excluded.updated_at WHERE saved_views.workspace_id=excluded.workspace_id").bind(id,workspaceId,text(raw,['objectType','object_type'],128,true),text(raw,['name'],200,true),json(raw,['filters','filters_json'],[]),value(raw,'sort','sort_json')==null?null:json(raw,['sort','sort_json'],null),created,updated).run();await ensureChange(result,env,workspaceId,'saved_views',id);return id;}
  const fileId=ref(raw,['fileId','file_id'],true)!,recordType=text(raw,['recordType','record_type'],128,true)!,recordId=ref(raw,['recordId','record_id'],true)!;await requireTenantRow(env,workspaceId,'crm_files',fileId,'file');await requireTarget(env,workspaceId,recordType,recordId);await env.CRM_DB!.prepare("INSERT OR IGNORE INTO crm_file_links (file_id,workspace_id,record_type,record_id,created_at) VALUES (?,?,?,?,?)").bind(fileId,workspaceId,recordType,recordId,created).run();return `${fileId}:${recordType}:${recordId}`;
}

export async function previewImportRecords(env:Env,workspaceId:string,type:CrmImportType,records:Record<string,unknown>[],mapping:ImportMapping){const rows=[];let valid=0,invalid=0;for(const[index,record]of records.slice(0,50).entries()){const mapped=mapImportRecord(type,record,mapping),errors:string[]=[];try{const fakeDb={prepare(){return{bind(){return{first:async()=>({exists:1}),run:async()=>({success:true,meta:{changes:1}})}}} as unknown as D1PreparedStatement;}} as unknown as D1Database;const previewEnv={...env,CRM_DB:fakeDb,STORAGE:{...env.STORAGE,head:async()=>({})} as unknown as R2Bucket};await writeImportRecord(previewEnv,workspaceId,type,{...mapped,id:validId(mapped.id)?mapped.id:'preview-id'},'2026-01-01T00:00:00.000Z');}catch(error){errors.push(String(error instanceof Error?error.message:error).slice(0,200));}if(errors.length)invalid++;else valid++;rows.push({index,valid:errors.length===0,mapped,errors});}return{fields:fields[type],valid,invalid,rows};}

export async function processImportChunk(env:Env,params:CrmImportParams):Promise<{done:boolean;cursor:number;processed:number;failed:number}>{
  const row=await env.CRM_DB!.prepare("SELECT status,cursor,object_key as objectKey,object_type as objectType,bytes,mapping_json as mappingJson FROM migration_runs WHERE id=? AND workspace_id=?").bind(params.importId,params.workspaceId).first<{status:string;cursor:string|null;objectKey:string;objectType:string;bytes:number;mappingJson:string}>();if(!row||!row.objectKey||!isCrmImportType(row.objectType))throw new Error('import run not found');if(row.status==='cancelled')return{done:true,cursor:Number(row.cursor??0),processed:0,failed:0};
  let mapping:ImportMapping={};try{mapping=object(JSON.parse(row.mappingJson||'{}')) as ImportMapping;}catch{throw new Error('invalid import mapping');}const offset=Math.max(0,Number(row.cursor??0));if(!Number.isSafeInteger(offset)||offset>row.bytes)throw new Error('invalid import cursor');if(offset===row.bytes)return{done:true,cursor:offset,processed:0,failed:0};
  const length=Math.min(CHUNK_BYTES,row.bytes-offset),source=await env.STORAGE.get(row.objectKey,{range:{offset,length}});if(!source)throw new Error('import source missing');const bytes=new Uint8Array(await source.arrayBuffer());let consumed=bytes.byteLength,newlines=0;for(let i=0;i<bytes.byteLength;i++)if(bytes[i]===10&&++newlines===MAX_RECORDS_PER_STEP){consumed=i+1;break;}if(consumed===bytes.byteLength&&offset+bytes.byteLength<row.bytes){const newline=bytes.lastIndexOf(10);if(newline<0){if(bytes.byteLength>=MAX_RECORD_BYTES)throw new Error('import record exceeds 1 MiB');return{done:false,cursor:offset,processed:0,failed:0};}consumed=newline+1;}
  const lines=new TextDecoder('utf-8',{fatal:true,ignoreBOM:false}).decode(bytes.slice(0,consumed)).split('\n').filter(line=>line.trim());let processed=0,failed=0;const errors:Array<{offset:number;message:string}>=[],now=new Date().toISOString();for(const[index,line]of lines.entries()){try{const decoded=object(JSON.parse(line));if(decoded.kind==='manifest'||decoded.kind==='summary')continue;const importedType:string=decoded.kind==='record'?String(decoded.objectType??row.objectType):String(row.objectType);if(importedType!==row.objectType)throw new Error(`unexpected object type ${importedType}`);await writeImportRecord(env,params.workspaceId,row.objectType,mapImportRecord(row.objectType,decoded.kind==='record'?object(decoded.record):decoded,mapping),now);processed++;}catch(error){failed++;errors.push({offset:offset+index,message:String(error instanceof Error?error.message:error).slice(0,200)});}}
  const cursor=offset+consumed,done=cursor>=row.bytes;let errorKey:null|string=null;if(errors.length){errorKey=`imports/${params.workspaceId}/${params.importId}/errors-${offset}.json`;await env.STORAGE.put(errorKey,JSON.stringify({importId:params.importId,offset,errors}),{httpMetadata:{contentType:'application/json'},customMetadata:{workspaceId:params.workspaceId,importId:params.importId}});}await env.CRM_DB!.prepare("UPDATE migration_runs SET status=?,cursor=?,processed=processed+?,failed=failed+?,error_object_key=COALESCE(?,error_object_key),updated_at=? WHERE id=? AND workspace_id=? AND status='running'").bind(done?'completed':'running',String(cursor),processed,failed,errorKey,now,params.importId,params.workspaceId).run();return{done,cursor,processed,failed};
}
