import type {Env} from './types';
type Row=Record<string,any>;type Vars=Record<string,unknown>;
const object=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const root=(query:string,fallback:string)=>query.match(/\{\s*([A-Za-z_][A-Za-z0-9_]*)/)?.[1]??fallback;
const value=(row:Row)=>({__typename:'Notification',id:row.id,type:row.notification_type,title:row.title,body:row.body,data:row.data_json?JSON.parse(row.data_json):{},readAt:row.read_at,archivedAt:row.archived_at,createdAt:row.created_at,updatedAt:row.updated_at});
const fail=(message:string,status=400)=>Response.json({errors:[{message}]},{status});
export async function crmNotifications(op:string,query:string,vars:Vars,env:Env,workspaceId:string,role:string,actor:string):Promise<Response|null>{
  if(!/^(FindManyNotifications|GetNotifications|NotificationUnreadCount|CreateNotification|MarkNotificationsAsRead|MarkAllNotificationsAsRead|ArchiveNotification|ArchiveNotifications)$/.test(op))return null;
  const db=env.CRM_DB!;const responseKey=root(query,op[0].toLowerCase()+op.slice(1));const ok=(payload:unknown)=>Response.json({data:{[responseKey]:payload}});
  if(op==='FindManyNotifications'||op==='GetNotifications'){
    const limit=Number(vars.first??vars.limit??30),offset=Number(vars.offset??0);if(!Number.isInteger(limit)||limit<1||limit>100||!Number.isInteger(offset)||offset<0)return fail('Invalid notification page');
    const includeArchived=vars.includeArchived===true;const [rows,count,unread]=await Promise.all([db.prepare(`SELECT * FROM crm_notifications WHERE workspace_id=? AND recipient_subject=? ${includeArchived?'':'AND archived_at IS NULL'} ORDER BY created_at DESC,id LIMIT ? OFFSET ?`).bind(workspaceId,actor,limit,offset).all<Row>(),db.prepare(`SELECT COUNT(*) AS count FROM crm_notifications WHERE workspace_id=? AND recipient_subject=? ${includeArchived?'':'AND archived_at IS NULL'}`).bind(workspaceId,actor).first<{count:number}>(),db.prepare('SELECT COUNT(*) AS count FROM crm_notifications WHERE workspace_id=? AND recipient_subject=? AND archived_at IS NULL AND read_at IS NULL').bind(workspaceId,actor).first<{count:number}>()]);const nodes=rows.results.map(value);return ok({__typename:'NotificationConnection',nodes,edges:nodes.map((node,index)=>({node,cursor:btoa(String(offset+index))})),totalCount:Number(count?.count??0),unreadCount:Number(unread?.count??0),pageInfo:{hasNextPage:offset+nodes.length<Number(count?.count??0),hasPreviousPage:offset>0}});
  }
  if(op==='NotificationUnreadCount'){const row=await db.prepare('SELECT COUNT(*) AS count FROM crm_notifications WHERE workspace_id=? AND recipient_subject=? AND archived_at IS NULL AND read_at IS NULL').bind(workspaceId,actor).first<{count:number}>();return ok(Number(row?.count??0));}
  if(op==='CreateNotification'){
    if(role!=='owner'&&role!=='admin')return fail('admin access required',403);const raw=object(vars.input)?vars.input:vars;const recipient=String(raw.recipientSubject??'');const member=await db.prepare("SELECT 1 FROM workspace_members WHERE workspace_id=? AND identity_subject=? AND status='active'").bind(workspaceId,recipient).first();if(!member)return fail('Recipient is not an active workspace member');const title=typeof raw.title==='string'?raw.title.trim().slice(0,240):'';if(!title)return fail('Notification title is required');const id=typeof raw.id==='string'?raw.id:crypto.randomUUID(),now=new Date().toISOString(),dedupe=typeof raw.dedupeKey==='string'?raw.dedupeKey.slice(0,200):null;await db.batch([db.prepare("INSERT INTO crm_notifications (id,workspace_id,recipient_subject,notification_type,title,body,data_json,dedupe_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,recipient_subject,dedupe_key) DO NOTHING").bind(id,workspaceId,recipient,String(raw.type??'SYSTEM').slice(0,80),title,typeof raw.body==='string'?raw.body.slice(0,5000):null,JSON.stringify(object(raw.data)?raw.data:{}),dedupe,now,now),db.prepare("INSERT OR IGNORE INTO crm_notification_deliveries (id,notification_id,workspace_id,channel,status,attempts,delivered_at,updated_at) VALUES (?,?,?,'in_app','delivered',1,?,?)").bind(crypto.randomUUID(),id,workspaceId,now,now)]).catch(async error=>{if(!dedupe)throw error;});const stored=await db.prepare('SELECT * FROM crm_notifications WHERE workspace_id=? AND recipient_subject=? AND (id=? OR dedupe_key=?) ORDER BY created_at DESC LIMIT 1').bind(workspaceId,recipient,id,dedupe).first<Row>();return ok(value(stored!));
  }
  const raw=object(vars.input)?vars.input:vars;const rawIds=Array.isArray(raw.ids)?raw.ids:typeof raw.id==='string'?[raw.id]:[];if(rawIds.length>100||rawIds.some(id=>typeof id!=='string'||id.length>128))return fail('Invalid notification IDs');const now=new Date().toISOString();
  if(op==='MarkAllNotificationsAsRead'){await db.prepare('UPDATE crm_notifications SET read_at=COALESCE(read_at,?),updated_at=? WHERE workspace_id=? AND recipient_subject=? AND archived_at IS NULL').bind(now,now,workspaceId,actor).run();return ok(true);}
  if(!rawIds.length)return fail('Notification IDs are required');const placeholders=rawIds.map(()=>'?').join(',');if(op==='MarkNotificationsAsRead'){await db.prepare(`UPDATE crm_notifications SET read_at=COALESCE(read_at,?),updated_at=? WHERE workspace_id=? AND recipient_subject=? AND id IN (${placeholders})`).bind(now,now,workspaceId,actor,...rawIds).run();return ok(true);}await db.prepare(`UPDATE crm_notifications SET archived_at=COALESCE(archived_at,?),updated_at=? WHERE workspace_id=? AND recipient_subject=? AND id IN (${placeholders})`).bind(now,now,workspaceId,actor,...rawIds).run();return ok(true);
}
