import { accessIdentityForRequest } from "./access";
import type { Env } from "./types";

type Vars = Record<string, unknown>;
type Entity = { table: string; singular: string; plural: string; columns: string[] };
const ENTITIES: Record<string, Entity> = {
  people: { table: "contacts", singular: "person", plural: "people", columns: ["id", "first_name", "last_name", "email", "created_at", "updated_at"] },
  person: { table: "contacts", singular: "person", plural: "people", columns: ["id", "first_name", "last_name", "email", "created_at", "updated_at"] },
  companies: { table: "companies", singular: "company", plural: "companies", columns: ["id", "name", "domain", "created_at", "updated_at"] },
  company: { table: "companies", singular: "company", plural: "companies", columns: ["id", "name", "domain", "created_at", "updated_at"] },
  opportunities: { table: "opportunities", singular: "opportunity", plural: "opportunities", columns: ["id", "name", "amount_cents", "stage", "company_id", "point_of_contact_id", "pipeline_id", "created_at", "updated_at"] },
  opportunity: { table: "opportunities", singular: "opportunity", plural: "opportunities", columns: ["id", "name", "amount_cents", "stage", "company_id", "point_of_contact_id", "pipeline_id", "created_at", "updated_at"] },
  activities: { table: "activities", singular: "activity", plural: "activities", columns: ["id", "type", "title", "body", "contact_id", "company_id", "opportunity_id", "due_at", "completed_at", "created_at", "updated_at"] },
  activity: { table: "activities", singular: "activity", plural: "activities", columns: ["id", "type", "title", "body", "contact_id", "company_id", "opportunity_id", "due_at", "completed_at", "created_at", "updated_at"] },
};
const camel = (key: string) => key.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
function mapRow(row: Record<string, unknown>): Record<string, unknown> { const out: Record<string, unknown> = {}; for (const [key, value] of Object.entries(row)) out[camel(key)] = value; if ("firstName" in out || "lastName" in out) out.name = { firstName: out.firstName ?? "", lastName: out.lastName ?? "" }; if ("amountCents" in out) out.amount = out.amountCents == null ? null : Number(out.amountCents) / 100; return out; }
function unwrapInput(vars: Vars): Record<string, unknown> { for (const key of ["input", "data", "record", "createInput", "updateInput"]) { const value = vars[key]; if (value && typeof value === "object" && !Array.isArray(value)) { const obj = value as Record<string, unknown>; return (obj.data && typeof obj.data === "object" ? obj.data : obj) as Record<string, unknown>; } } return vars; }
function operationName(body: { query?: string; operationName?: string }): string { return body.operationName || body.query?.match(/\b(?:query|mutation|subscription)\s+([A-Za-z0-9_]+)/)?.[1] || ""; }
function entityFor(op: string): Entity | null { const match = op.match(/(?:People|Person|Companies|Company|Opportunities|Opportunity|Activities|Activity)/i)?.[0].toLowerCase(); return match ? ENTITIES[match] ?? null : null; }
function entityFromVars(vars: Vars): Entity | null { const name = String(vars.objectName ?? vars.objectType ?? vars.recordType ?? vars.table ?? "").toLowerCase(); if (name.includes("person") || name.includes("contact")) return ENTITIES.people; if (name.includes("compan")) return ENTITIES.companies; if (name.includes("opportun") || name.includes("deal")) return ENTITIES.opportunities; if (name.includes("activ") || name.includes("task") || name.includes("note")) return ENTITIES.activities; return null; }
function valueFor(input: Record<string, unknown>, field: string): unknown { const aliases: Record<string, string[]> = { amount_cents: ["amountCents", "amount"], point_of_contact_id: ["pointOfContactId"], company_id: ["companyId"], pipeline_id: ["pipelineId"], contact_id: ["contactId"], opportunity_id: ["opportunityId"], due_at: ["dueAt"], completed_at: ["completedAt"] }; const value = input[field] ?? (aliases[field] ?? []).map((x) => input[x]).find((x) => x !== undefined); return field === "amount_cents" && typeof value === "number" ? Math.round(value * 100) : value; }
async function enrich(env: Env, workspaceId: string, entity: Entity, row: Record<string, unknown>): Promise<Record<string, unknown>> { const out = mapRow(row); if (entity.table === "opportunities") { if (row.company_id) out.company = await env.CRM_DB!.prepare("SELECT id, name, domain FROM companies WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.company_id).first(); if (row.point_of_contact_id) out.pointOfContact = await env.CRM_DB!.prepare("SELECT id, first_name as firstName, last_name as lastName, email FROM contacts WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.point_of_contact_id).first(); } if (entity.table === "activities") { if (row.contact_id) out.contact = await env.CRM_DB!.prepare("SELECT id, first_name as firstName, last_name as lastName, email FROM contacts WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.contact_id).first(); if (row.company_id) out.company = await env.CRM_DB!.prepare("SELECT id, name, domain FROM companies WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.company_id).first(); if (row.opportunity_id) out.opportunity = await env.CRM_DB!.prepare("SELECT id, name, stage FROM opportunities WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.opportunity_id).first(); } return out; }

/** Compatibility resolver for the upstream Twenty GraphQL client, backed only by tenant-scoped D1. */
export async function handleGraphql(request: Request, env: Env): Promise<Response | null> {
  if (new URL(request.url).pathname !== "/graphql" || request.method !== "POST") return null;
  const actor = await accessIdentityForRequest(request, env);
  if (!actor || !env.CRM_DB) return Response.json({ errors: [{ message: "unauthorized" }] }, { status: 401 });
  const body = (await request.json().catch(() => ({}))) as { query?: string; operationName?: string; variables?: Vars }; const op = operationName(body); const vars = body.variables ?? {};
  if (op === "IntrospectionQuery" || /__schema|__type/.test(body.query ?? "")) return Response.json({ data: { __schema: { queryType: { name: "Query" }, mutationType: { name: "Mutation" }, types: [] } } });
  const workspaceId = request.headers.get("x-workspace-id") || String(vars.workspaceId ?? ((vars.workspace && typeof vars.workspace === "object") ? (vars.workspace as Record<string, unknown>).id : "") ?? "");
  if (!workspaceId) return Response.json({ errors: [{ message: "x-workspace-id required" }] }, { status: 400 });
  const member = await env.CRM_DB.prepare("SELECT role FROM workspace_members WHERE workspace_id = ? AND identity_subject = ? AND status = 'active' LIMIT 1").bind(workspaceId, actor.subject).first<{ role: string }>(); if (!member) return Response.json({ errors: [{ message: "forbidden" }] }, { status: 403 });
  if (/GetCurrentUser|CurrentUser|^Me/i.test(op)) return Response.json({ data: { currentUser: { id: actor.subject, userId: actor.subject, email: actor.email ?? null, name: { firstName: (actor.email ?? "").split("@")[0], lastName: "" } } } });
  if (/Metadata/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, object_key as name, label, plural_label as pluralLabel, created_at as createdAt, updated_at as updatedAt FROM custom_objects WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); const fields = await env.CRM_DB.prepare("SELECT id, object_type as objectType, field_key as name, label, field_type as type, options_json as options, created_at as createdAt FROM custom_fields WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); return Response.json({ data: { objectMetadataItems: rows.results, objects: rows.results, fieldMetadataItems: fields.results, fields: fields.results, minimalMetadata: { objects: rows.results, fields: fields.results } } }); }
  if (/View/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, object_type as objectType, name, filters_json as filters, sort_json as sort, created_at as createdAt, updated_at as updatedAt FROM saved_views WHERE workspace_id = ? ORDER BY updated_at DESC").bind(workspaceId).all(); return Response.json({ data: { views: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length }, findManyViews: rows.results } }); }
  if (/FieldMetadata/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, object_type as objectType, field_key as name, label, field_type as type, options_json as options, created_at as createdAt FROM custom_fields WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); return Response.json({ data: { fieldMetadataItems: rows.results, fields: rows.results } }); }
  if (/Search|CombinedFindManyRecords/i.test(op)) {
    const term = String(vars.searchTerm ?? vars.query ?? vars.q ?? "").slice(0, 120); const pattern = `%${term}%`;
    const [people, companies, opportunities] = await env.CRM_DB.batch([
      env.CRM_DB.prepare("SELECT id, first_name || ' ' || last_name AS name, email, 'person' AS objectType FROM contacts WHERE workspace_id = ? AND (first_name LIKE ? OR last_name LIKE ? OR email LIKE ?) LIMIT 25").bind(workspaceId, pattern, pattern, pattern),
      env.CRM_DB.prepare("SELECT id, name, domain, 'company' AS objectType FROM companies WHERE workspace_id = ? AND (name LIKE ? OR domain LIKE ?) LIMIT 25").bind(workspaceId, pattern, pattern),
      env.CRM_DB.prepare("SELECT id, name, stage, 'opportunity' AS objectType FROM opportunities WHERE workspace_id = ? AND (name LIKE ? OR stage LIKE ?) LIMIT 25").bind(workspaceId, pattern, pattern),
    ]); const results = people.results.concat(companies.results, opportunities.results); return Response.json({ data: { search: results, combinedFindManyRecords: results, records: results } });
  }
  if (/Aggregate|ObjectRecordCounts|Count/i.test(op)) {
    const entity = entityFor(op); const count = entity ? await env.CRM_DB.prepare(`SELECT COUNT(*) AS count FROM ${entity.table} WHERE workspace_id = ?`).bind(workspaceId).first<{ count: number }>() : null;
    return Response.json({ data: { aggregate: { count: Number(count?.count ?? 0) }, objectRecordCounts: count ? [{ objectName: entity?.plural, count: Number(count.count) }] : [] } });
  }
  if (/Workspace/i.test(op) && !entityFor(op)) { const workspace = await env.CRM_DB.prepare("SELECT id, name, created_at as createdAt FROM workspaces WHERE id = ?").bind(workspaceId).first(); return Response.json({ data: { workspace, currentWorkspace: workspace, workspaces: { edges: workspace ? [{ node: workspace }] : [], nodes: workspace ? [workspace] : [], totalCount: workspace ? 1 : 0 } } }); }
  const entity = entityFor(op) ?? entityFromVars(vars); if (!entity) return Response.json({ data: {} });
  const input = unwrapInput(vars); const id = String(vars.id ?? vars.idToFind ?? vars.recordId ?? input.id ?? "");
  if (/Delete|Destroy|Archive/i.test(op)) { if (!id) return Response.json({ errors: [{ message: "id required" }] }, { status: 400 }); await env.CRM_DB.prepare(`DELETE FROM ${entity.table} WHERE workspace_id = ? AND id = ?`).bind(workspaceId, id).run(); return Response.json({ data: { [entity.singular]: { id }, [`delete${entity.singular[0].toUpperCase()}${entity.singular.slice(1)}`]: { id } } }); }
  if (/Create|Update|Upsert|Merge/i.test(op)) { const now = new Date().toISOString(); const recordId = id || crypto.randomUUID(); const fields = entity.columns.filter((column) => !["id", "created_at", "updated_at"].includes(column)).filter((column) => valueFor(input, column) !== undefined); if (/Create|Upsert/i.test(op) && !id) { const names = ["id", "workspace_id", ...fields, "created_at", "updated_at"]; const values = [recordId, workspaceId, ...fields.map((f) => valueFor(input, f)), now, now]; await env.CRM_DB.prepare(`INSERT INTO ${entity.table} (${names.join(",")}) VALUES (${names.map(() => "?").join(",")})`).bind(...values).run(); } else if (fields.length) await env.CRM_DB.prepare(`UPDATE ${entity.table} SET ${fields.map((f) => `${f} = ?`).join(",")}, updated_at = ? WHERE workspace_id = ? AND id = ?`).bind(...fields.map((f) => valueFor(input, f)), now, workspaceId, recordId).run(); const row = await env.CRM_DB.prepare(`SELECT * FROM ${entity.table} WHERE workspace_id = ? AND id = ?`).bind(workspaceId, recordId).first<Record<string, unknown>>(); return Response.json({ data: { [entity.singular]: row ? mapRow(row) : { id: recordId } } }); }
  const limit = Math.min(100, Math.max(1, Number(vars.first ?? vars.limit ?? 25))); const offset = Math.max(0, Number(vars.offset ?? vars.skip ?? 0)); const one = /^FindOne|^GetOne|^FindDuplicate/i.test(op) || (!!id && !/^FindMany|^GetMany|^FindAll/i.test(op));
  if (one) { const row = await env.CRM_DB.prepare(`SELECT * FROM ${entity.table} WHERE workspace_id = ? AND id = ?`).bind(workspaceId, id).first<Record<string, unknown>>(); return Response.json({ data: { [entity.singular]: row ? await enrich(env, workspaceId, entity, row) : null } }); }
  const rows = await env.CRM_DB.prepare(`SELECT * FROM ${entity.table} WHERE workspace_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(workspaceId, limit, offset).all<Record<string, unknown>>(); const nodes = await Promise.all(rows.results.map((row) => enrich(env, workspaceId, entity, row))); const connection = { edges: nodes.map((node) => ({ node, cursor: String(node.id ?? "") })), nodes, pageInfo: { hasNextPage: nodes.length === limit, hasPreviousPage: offset > 0, startCursor: nodes[0]?.id ?? null, endCursor: nodes.at(-1)?.id ?? null }, totalCount: nodes.length }; return Response.json({ data: { [entity.plural]: connection, ...(entity.plural === "people" ? { contacts: connection } : {}) } });
}
