import { accessIdentityForRequest } from "./access";
import type { Env } from "./types";

type Vars = Record<string, unknown>;
type Entity = { table: string; singular: string; plural: string; columns: string[] };
const ENTITIES: Record<string, Entity> = {
  people: { table: "contacts", singular: "person", plural: "people", columns: ["id", "first_name", "last_name", "email", "created_at", "updated_at"] },
  person: { table: "contacts", singular: "person", plural: "people", columns: ["id", "first_name", "last_name", "email", "created_at", "updated_at"] },
  companies: { table: "companies", singular: "company", plural: "companies", columns: ["id", "name", "domain", "created_at", "updated_at"] },
  company: { table: "companies", singular: "company", plural: "companies", columns: ["id", "name", "domain", "created_at", "updated_at"] },
  opportunities: { table: "opportunities", singular: "opportunity", plural: "opportunities", columns: ["id", "name", "amount_cents", "stage", "company_id", "point_of_contact_id", "pipeline_id", "created_at", "updated_at"] },
  opportunity: { table: "opportunities", singular: "opportunity", plural: "opportunities", columns: ["id", "name", "amount_cents", "stage", "company_id", "point_of_contact_id", "pipeline_id", "created_at", "updated_at"] },
  activities: { table: "activities", singular: "activity", plural: "activities", columns: ["id", "type", "title", "body", "contact_id", "company_id", "opportunity_id", "due_at", "completed_at", "created_at", "updated_at"] },
  activity: { table: "activities", singular: "activity", plural: "activities", columns: ["id", "type", "title", "body", "contact_id", "company_id", "opportunity_id", "due_at", "completed_at", "created_at", "updated_at"] },
};
const camel = (key: string) => key.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
function mapRow(row: Record<string, unknown>): Record<string, unknown> { const out: Record<string, unknown> = {}; for (const [key, value] of Object.entries(row)) out[camel(key)] = value; if ("firstName" in out || "lastName" in out) out.name = { firstName: out.firstName ?? "", lastName: out.lastName ?? "" }; if ("amountCents" in out) out.amount = out.amountCents == null ? null : Number(out.amountCents) / 100; return out; }
function unwrapInput(vars: Vars): Record<string, unknown> { for (const key of ["input", "data", "record", "createInput", "updateInput"]) { const value = vars[key]; if (value && typeof value === "object" && !Array.isArray(value)) { const obj = value as Record<string, unknown>; return (obj.data && typeof obj.data === "object" ? obj.data : obj) as Record<string, unknown>; } } return vars; }
function operationName(body: { query?: string; operationName?: string }): string { return body.operationName || body.query?.match(/\b(?:query|mutation|subscription)\s+([A-Za-z0-9_]+)/)?.[1] || ""; }
function rootField(query?: string): string | null { const match = query?.match(/\{\s*([A-Za-z_][A-Za-z0-9_]*)/); return match?.[1] ?? null; }
function entityFor(op: string): Entity | null { const match = op.match(/(?:People|Person|Companies|Company|Opportunities|Opportunity|Activities|Activity)/i)?.[0].toLowerCase(); return match ? ENTITIES[match] ?? null : null; }
function entityFromVars(vars: Vars): Entity | null { const name = String(vars.objectName ?? vars.objectType ?? vars.recordType ?? vars.table ?? "").toLowerCase(); if (name.includes("person") || name.includes("contact")) return ENTITIES.people; if (name.includes("compan")) return ENTITIES.companies; if (name.includes("opportun") || name.includes("deal")) return ENTITIES.opportunities; if (name.includes("activ") || name.includes("task") || name.includes("note")) return ENTITIES.activities; return null; }
function customObjectKey(vars: Vars): string | null { const raw = String(vars.objectName ?? vars.objectType ?? vars.customObjectKey ?? "").trim().toLowerCase(); return /^[a-z][a-z0-9_]{0,63}$/.test(raw) && !entityFromVars(vars) ? raw : null; }
function valueFor(input: Record<string, unknown>, field: string): unknown { const aliases: Record<string, string[]> = { amount_cents: ["amountCents", "amount"], point_of_contact_id: ["pointOfContactId"], company_id: ["companyId"], pipeline_id: ["pipelineId"], contact_id: ["contactId"], opportunity_id: ["opportunityId"], due_at: ["dueAt"], completed_at: ["completedAt"] }; const value = input[field] ?? (aliases[field] ?? []).map((x) => input[x]).find((x) => x !== undefined); return field === "amount_cents" && typeof value === "number" ? Math.round(value * 100) : value; }
async function sha256(value: string): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join(""); }
async function enrich(env: Env, workspaceId: string, entity: Entity, row: Record<string, unknown>): Promise<Record<string, unknown>> { const out = mapRow(row); if (entity.table === "opportunities") { if (row.company_id) out.company = await env.CRM_DB!.prepare("SELECT id, name, domain FROM companies WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.company_id).first(); if (row.point_of_contact_id) out.pointOfContact = await env.CRM_DB!.prepare("SELECT id, first_name as firstName, last_name as lastName, email FROM contacts WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.point_of_contact_id).first(); } if (entity.table === "activities") { if (row.contact_id) out.contact = await env.CRM_DB!.prepare("SELECT id, first_name as firstName, last_name as lastName, email FROM contacts WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.contact_id).first(); if (row.company_id) out.company = await env.CRM_DB!.prepare("SELECT id, name, domain FROM companies WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.company_id).first(); if (row.opportunity_id) out.opportunity = await env.CRM_DB!.prepare("SELECT id, name, stage FROM opportunities WHERE workspace_id = ? AND id = ?").bind(workspaceId, row.opportunity_id).first(); } return out; }

/** Compatibility resolver for the upstream Twenty GraphQL client, backed only by tenant-scoped D1. */
export async function handleGraphql(request: Request, env: Env): Promise<Response | null> {
  if (new URL(request.url).pathname !== "/graphql" || request.method !== "POST") return null;
  const actor = await accessIdentityForRequest(request, env);
  if (!actor || !env.CRM_DB) return Response.json({ errors: [{ message: "unauthorized" }] }, { status: 401 });
  const body = (await request.json().catch(() => ({}))) as { query?: string; operationName?: string; variables?: Vars }; const op = operationName(body); const vars = body.variables ?? {};
  if (op === "IntrospectionQuery" || /__schema|__type/.test(body.query ?? "")) return Response.json({ data: { __schema: { queryType: { name: "Query" }, mutationType: { name: "Mutation" }, types: [] } } });
  const workspaceId = request.headers.get("x-workspace-id") || String(vars.workspaceId ?? ((vars.workspace && typeof vars.workspace === "object") ? (vars.workspace as Record<string, unknown>).id : "") ?? "");
  if (!workspaceId) return Response.json({ errors: [{ message: "x-workspace-id required" }] }, { status: 400 });
  const member = await env.CRM_DB.prepare("SELECT role FROM workspace_members WHERE workspace_id = ? AND identity_subject = ? AND status = 'active' LIMIT 1").bind(workspaceId, actor.subject).first<{ role: string }>(); if (!member) return Response.json({ errors: [{ message: "forbidden" }] }, { status: 403 });
  if (/GetCurrentUser|CurrentUser|^Me/i.test(op)) return Response.json({ data: { currentUser: { id: actor.subject, userId: actor.subject, email: actor.email ?? null, name: { firstName: (actor.email ?? "").split("@")[0], lastName: "" } } } });
  if (/Session/i.test(op) || /SignOut|SignIn|RenewToken|RevokeAllOtherUserSessions/i.test(op)) { const now = new Date().toISOString(); if (/RevokeUserSession|SignOut|RevokeAllOther/i.test(op)) { const sessionId = String(vars.sessionId ?? vars.id ?? ""); if (sessionId) await env.CRM_DB.prepare("UPDATE native_sessions SET revoked_at = ? WHERE workspace_id = ? AND identity_subject = ? AND id = ?").bind(now, workspaceId, actor.subject, sessionId).run(); } const rows = await env.CRM_DB.prepare("SELECT id, created_at as createdAt, last_seen_at as lastSeenAt, expires_at as expiresAt, revoked_at as revokedAt FROM native_sessions WHERE workspace_id = ? AND identity_subject = ? ORDER BY created_at DESC LIMIT 50").bind(workspaceId, actor.subject).all(); return Response.json({ data: { currentUserSessions: rows.results, sessions: rows.results, revokeUserSession: { success: true }, signOut: { success: true }, renewToken: { success: true } } }); }
  if (/ChatThread|ChatMessage|AgentChat/i.test(op)) {
    const input = unwrapInput(vars); const threadId = String(vars.threadId ?? input.threadId ?? vars.id ?? "");
    if (/CreateChatThread|StartWorkspaceSetupChat/i.test(op)) { const id = crypto.randomUUID(); const now = new Date().toISOString(); await env.CRM_DB.prepare("INSERT INTO ai_chat_threads (id, workspace_id, title, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)").bind(id, workspaceId, String(input.title ?? "New chat").slice(0, 200), actor.subject, now, now).run(); return Response.json({ data: { createChatThread: { id, title: input.title ?? "New chat", status: "active", createdAt: now, updatedAt: now } } }); }
    if (/SendChatMessage|AnswerAgentChatQuestion/i.test(op)) { const id = threadId || crypto.randomUUID(); const content = String(input.content ?? input.message ?? input.question ?? "").slice(0, 10000); const now = new Date().toISOString(); if (!threadId) await env.CRM_DB.prepare("INSERT INTO ai_chat_threads (id, workspace_id, title, created_by, created_at, updated_at) VALUES (?, ?, 'New chat', ?, ?, ?)").bind(id, workspaceId, actor.subject, now, now).run(); await env.CRM_DB.prepare("INSERT INTO ai_chat_messages (id, thread_id, workspace_id, role, content, created_at) VALUES (?, ?, ?, 'user', ?, ?)").bind(crypto.randomUUID(), id, workspaceId, content, now).run(); try { await env.JOBS_QUEUE.send({ schemaVersion: 1 as const, id: crypto.randomUUID(), queueName: "twenty-jobs", jobName: "ai.chat", data: { threadId: id, workspaceId, content }, createdAt: now, retryLimit: 3, priority: 0 }); } catch { /* message is durably stored */ } return Response.json({ data: { sendChatMessage: { id, threadId: id, status: "queued" }, answerAgentChatQuestion: { id, threadId: id, status: "queued" } } }); }
    if (/RenameChatThread/i.test(op) && threadId) { await env.CRM_DB.prepare("UPDATE ai_chat_threads SET title = ?, updated_at = ? WHERE workspace_id = ? AND id = ?").bind(String(input.title ?? "Chat").slice(0, 200), new Date().toISOString(), workspaceId, threadId).run(); }
    if (/ArchiveChatThread|UnarchiveChatThread/i.test(op) && threadId) await env.CRM_DB.prepare("UPDATE ai_chat_threads SET status = ?, updated_at = ? WHERE workspace_id = ? AND id = ?").bind(/Unarchive/.test(op) ? "active" : "archived", new Date().toISOString(), workspaceId, threadId).run();
    if (/DeleteChatThread/i.test(op) && threadId) await env.CRM_DB.prepare("DELETE FROM ai_chat_threads WHERE workspace_id = ? AND id = ?").bind(workspaceId, threadId).run();
    if (/GetChatMessages/i.test(op) && threadId) { const rows = await env.CRM_DB.prepare("SELECT id, role, content, created_at as createdAt FROM ai_chat_messages WHERE workspace_id = ? AND thread_id = ? ORDER BY created_at").bind(workspaceId, threadId).all(); return Response.json({ data: { chatMessages: rows.results, messages: rows.results } }); }
    const rows = await env.CRM_DB.prepare("SELECT id, title, status, created_by as createdBy, created_at as createdAt, updated_at as updatedAt FROM ai_chat_threads WHERE workspace_id = ? ORDER BY updated_at DESC LIMIT 100").bind(workspaceId).all(); return Response.json({ data: { chatThreads: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length }, threads: rows.results } });
  }
  if (/ApiKey/i.test(op)) {
    if (/GetApiKeys|FindMany/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, name, created_at as createdAt, last_used_at as lastUsedAt, revoked_at as revokedAt FROM native_api_keys WHERE workspace_id = ? ORDER BY created_at DESC").bind(workspaceId).all(); return Response.json({ data: { apiKeys: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length } } }); }
    if (/GetApiKey|FindOne/i.test(op)) { const keyId = String(vars.id ?? vars.apiKeyId ?? ""); const row = await env.CRM_DB.prepare("SELECT id, name, created_at as createdAt, last_used_at as lastUsedAt, revoked_at as revokedAt FROM native_api_keys WHERE workspace_id = ? AND id = ?").bind(workspaceId, keyId).first(); return Response.json({ data: { apiKey: row } }); }
    const input = unwrapInput(vars); const keyId = String(vars.id ?? vars.apiKeyId ?? input.id ?? "");
    if (/Create|Generate/i.test(op)) { const id = crypto.randomUUID(); const token = `twenty_${crypto.randomUUID().replace(/-/g, "")}`; const now = new Date().toISOString(); await env.CRM_DB.prepare("INSERT INTO native_api_keys (id, workspace_id, name, token_hash, created_at) VALUES (?, ?, ?, ?, ?)").bind(id, workspaceId, String(input.name ?? "API key").slice(0, 120), await sha256(token), now).run(); return Response.json({ data: { createApiKey: { id, name: String(input.name ?? "API key"), token, createdAt: now } } }); }
    if (/Revoke|Delete/i.test(op) && keyId) { await env.CRM_DB.prepare("UPDATE native_api_keys SET revoked_at = ? WHERE workspace_id = ? AND id = ?").bind(new Date().toISOString(), workspaceId, keyId).run(); return Response.json({ data: { revokeApiKey: { id: keyId }, deleteApiKey: { id: keyId } } }); }
    if (/Update/i.test(op) && keyId) { await env.CRM_DB.prepare("UPDATE native_api_keys SET name = ? WHERE workspace_id = ? AND id = ?").bind(String(input.name ?? "API key").slice(0, 120), workspaceId, keyId).run(); return Response.json({ data: { updateApiKey: { id: keyId, name: input.name } } }); }
  }
  if (/Webhook/i.test(op)) { const input = unwrapInput(vars); const webhookId = String(vars.id ?? vars.webhookId ?? input.id ?? ""); if (/GetWebhooks|FindMany/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, name, url, events_json as events, active, created_at as createdAt, updated_at as updatedAt FROM native_webhooks WHERE workspace_id = ? ORDER BY updated_at DESC").bind(workspaceId).all(); return Response.json({ data: { webhooks: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length } } }); } if (/Create/i.test(op)) { const id = crypto.randomUUID(); const now = new Date().toISOString(); const url = String(input.url ?? ""); if (!/^https:\/\//.test(url)) return Response.json({ errors: [{ message: "webhook URL must use HTTPS" }] }, { status: 400 }); await env.CRM_DB.prepare("INSERT INTO native_webhooks (id, workspace_id, name, url, events_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(id, workspaceId, String(input.name ?? "Webhook").slice(0, 120), url.slice(0, 2000), JSON.stringify(input.events ?? []), now, now).run(); return Response.json({ data: { createWebhook: { id, name: input.name ?? "Webhook", url, active: true, createdAt: now, updatedAt: now } } }); } if (/Update/i.test(op) && webhookId) { const now = new Date().toISOString(); await env.CRM_DB.prepare("UPDATE native_webhooks SET name = COALESCE(?, name), url = COALESCE(?, url), events_json = COALESCE(?, events_json), active = COALESCE(?, active), updated_at = ? WHERE workspace_id = ? AND id = ?").bind(input.name ? String(input.name).slice(0, 120) : null, input.url ? String(input.url).slice(0, 2000) : null, input.events ? JSON.stringify(input.events) : null, input.active === undefined ? null : input.active ? 1 : 0, now, workspaceId, webhookId).run(); return Response.json({ data: { updateWebhook: { id: webhookId, updatedAt: now } } }); } if (/Delete/i.test(op) && webhookId) { await env.CRM_DB.prepare("DELETE FROM native_webhooks WHERE workspace_id = ? AND id = ?").bind(workspaceId, webhookId).run(); return Response.json({ data: { deleteWebhook: { id: webhookId } } }); } }
  if (/ApprovedAccessDomain|PublicDomain/i.test(op)) { const input = unwrapInput(vars); const domainId = String(vars.id ?? vars.domainId ?? input.id ?? ""); if (/Get|FindMany/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, domain, created_at as createdAt FROM approved_access_domains WHERE workspace_id = ? ORDER BY created_at DESC").bind(workspaceId).all(); return Response.json({ data: { approvedAccessDomains: rows.results, publicDomains: rows.results } }); } if (/Create|Add/i.test(op)) { const id = crypto.randomUUID(); const domain = String(input.domain ?? input.name ?? "").toLowerCase().trim(); if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domain)) return Response.json({ errors: [{ message: "invalid domain" }] }, { status: 400 }); await env.CRM_DB.prepare("INSERT OR IGNORE INTO approved_access_domains (id, workspace_id, domain, created_at) VALUES (?, ?, ?, ?)").bind(id, workspaceId, domain, new Date().toISOString()).run(); return Response.json({ data: { createApprovedAccessDomain: { id, domain } } }); } if (/Delete|Remove/i.test(op) && domainId) { await env.CRM_DB.prepare("DELETE FROM approved_access_domains WHERE workspace_id = ? AND id = ?").bind(workspaceId, domainId).run(); return Response.json({ data: { deleteApprovedAccessDomain: { id: domainId } } }); } }
  if (/ObjectMetadataItem|FieldMetadataItem/i.test(op) && /Create|Update|Delete/i.test(op)) { const input = unwrapInput(vars); const id = String(vars.id ?? input.id ?? ""); const now = new Date().toISOString(); if (/ObjectMetadataItem/i.test(op)) { if (/Create/i.test(op)) { const objectKey = String(input.name ?? input.objectKey ?? "custom_object").toLowerCase().replace(/[^a-z0-9_]/g, "_").slice(0, 64); const objectId = crypto.randomUUID(); await env.CRM_DB.prepare("INSERT INTO custom_objects (id, workspace_id, object_key, label, plural_label, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(objectId, workspaceId, objectKey, String(input.label ?? objectKey).slice(0, 120), String(input.pluralLabel ?? `${objectKey}s`).slice(0, 120), now, now).run(); return Response.json({ data: { createOneObjectMetadataItem: { id: objectId, name: objectKey, label: input.label ?? objectKey } } }); } if (/Delete/i.test(op) && id) await env.CRM_DB.prepare("DELETE FROM custom_objects WHERE workspace_id = ? AND id = ?").bind(workspaceId, id).run(); else if (/Update/i.test(op) && id) await env.CRM_DB.prepare("UPDATE custom_objects SET label = COALESCE(?, label), plural_label = COALESCE(?, plural_label), updated_at = ? WHERE workspace_id = ? AND id = ?").bind(input.label ? String(input.label).slice(0, 120) : null, input.pluralLabel ? String(input.pluralLabel).slice(0, 120) : null, now, workspaceId, id).run(); return Response.json({ data: { updateOneObjectMetadataItem: { id }, deleteOneObjectMetadataItem: { id } } }); } const objectType = String(input.objectType ?? input.objectMetadataId ?? "contact").toLowerCase(); const fieldId = id || crypto.randomUUID(); const fieldKey = String(input.name ?? input.fieldKey ?? `custom_${fieldId.slice(0, 8)}`).toLowerCase().replace(/[^a-z0-9_]/g, "_").slice(0, 64); if (/Create/i.test(op)) await env.CRM_DB.prepare("INSERT INTO custom_fields (id, workspace_id, object_type, field_key, label, field_type, options_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(fieldId, workspaceId, objectType, fieldKey, String(input.label ?? fieldKey).slice(0, 120), String(input.type ?? "text").toLowerCase(), input.options ? JSON.stringify(input.options) : null, now).run(); else if (/Delete/i.test(op)) await env.CRM_DB.prepare("DELETE FROM custom_fields WHERE workspace_id = ? AND id = ?").bind(workspaceId, fieldId).run(); else await env.CRM_DB.prepare("UPDATE custom_fields SET label = COALESCE(?, label), updated_at = updated_at WHERE workspace_id = ? AND id = ?").bind(input.label ? String(input.label).slice(0, 120) : null, workspaceId, fieldId).run(); return Response.json({ data: { createOneField: { id: fieldId, name: fieldKey }, updateOneField: { id: fieldId }, deleteOneField: { id: fieldId } } }); }
  if (/SSOIdentityProvider|IdentityProvider/i.test(op)) { const input = unwrapInput(vars); const providerId = String(vars.id ?? vars.providerId ?? input.id ?? ""); if (/Get|FindMany/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, provider_type as providerType, name, config_json as config, active, created_at as createdAt, updated_at as updatedAt FROM sso_identity_providers WHERE workspace_id = ? ORDER BY created_at DESC").bind(workspaceId).all(); return Response.json({ data: { ssoIdentityProviders: rows.results, identityProviders: rows.results } }); } if (/Create/i.test(op)) { const id = crypto.randomUUID(); const now = new Date().toISOString(); const type = /Oidc/i.test(op) ? "oidc" : "saml"; await env.CRM_DB.prepare("INSERT INTO sso_identity_providers (id, workspace_id, provider_type, name, config_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(id, workspaceId, type, String(input.name ?? `${type.toUpperCase()} provider`).slice(0, 120), JSON.stringify(input), now, now).run(); return Response.json({ data: { createSamlSsoIdentityProvider: { id, providerType: type }, createOidcSsoIdentityProvider: { id, providerType: type } } }); } if (/Delete|Remove/i.test(op) && providerId) { await env.CRM_DB.prepare("DELETE FROM sso_identity_providers WHERE workspace_id = ? AND id = ?").bind(workspaceId, providerId).run(); return Response.json({ data: { deleteSsoIdentityProvider: { id: providerId } } }); } }
  if (/Application|MarketplaceApp|InstallApplication|UninstallApplication|ApplicationRegistration/i.test(op)) { const input = unwrapInput(vars); const appId = String(vars.id ?? vars.applicationId ?? input.id ?? ""); if (/FindMany|GetApplications|FindAll/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, slug, name, status, config_json as config, installed_at as installedAt, updated_at as updatedAt FROM installed_apps WHERE workspace_id = ? AND status != 'uninstalled' ORDER BY updated_at DESC").bind(workspaceId).all(); return Response.json({ data: { applications: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length }, installedApplications: rows.results } }); } if (/FindOne|GetApplication/i.test(op)) { const row = await env.CRM_DB.prepare("SELECT id, slug, name, status, config_json as config, installed_at as installedAt, updated_at as updatedAt FROM installed_apps WHERE workspace_id = ? AND id = ?").bind(workspaceId, appId).first(); return Response.json({ data: { application: row } }); } if (/Install/i.test(op)) { const now = new Date().toISOString(); const slug = String(input.slug ?? input.applicationSlug ?? input.name ?? appId ?? crypto.randomUUID()).toLowerCase().slice(0, 120); const id = appId || crypto.randomUUID(); await env.CRM_DB.prepare("INSERT INTO installed_apps (id, workspace_id, slug, name, status, config_json, installed_at, updated_at) VALUES (?, ?, ?, ?, 'installed', ?, ?, ?) ON CONFLICT(workspace_id, slug) DO UPDATE SET status = 'installed', updated_at = excluded.updated_at").bind(id, workspaceId, slug, String(input.name ?? slug).slice(0, 200), JSON.stringify(input.config ?? {}), now, now).run(); return Response.json({ data: { installApplication: { id, slug, status: "installed" } } }); } if (/Uninstall|Delete/i.test(op) && appId) { await env.CRM_DB.prepare("UPDATE installed_apps SET status = 'uninstalled', updated_at = ? WHERE workspace_id = ? AND id = ?").bind(new Date().toISOString(), workspaceId, appId).run(); return Response.json({ data: { uninstallApplication: { id: appId }, deleteApplication: { id: appId } } }); } }
  if (/GetVersionInfo|SystemHealth|UpgradeStatus|IndicatorHealth|GetQueueMetrics|UsageAnalytics/i.test(op)) return Response.json({ data: { versionInfo: { version: "cloudflare-d1", deploymentMode: "cloudflare-native" }, systemHealthStatus: { status: "ok" }, upgradeStatus: { status: "up-to-date" }, indicatorHealthStatus: { status: "healthy" }, queueMetrics: { pending: 0, failed: 0 }, usageAnalytics: [] } });
  if (/EventLogs|AdminPanelRecentUsers|UserLookupAdminPanel/i.test(op)) { if (member.role !== "owner" && member.role !== "admin") return Response.json({ errors: [{ message: "admin access required" }] }, { status: 403 }); if (/EventLogs/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, actor_subject as actorSubject, action, object_type as objectType, object_id as objectId, request_id as requestId, metadata_json as metadata, created_at as createdAt FROM crm_audit_events WHERE workspace_id = ? ORDER BY created_at DESC LIMIT 500").bind(workspaceId).all(); return Response.json({ data: { eventLogs: rows.results, eventLogsLive: rows.results } }); } const rows = await env.CRM_DB.prepare("SELECT identity_subject as id, identity_subject as subject, role, status, created_at as createdAt FROM workspace_members WHERE workspace_id = ? ORDER BY created_at DESC LIMIT 100").bind(workspaceId).all(); return Response.json({ data: { adminPanelRecentUsers: rows.results, users: rows.results } }); }
  if (/Billing|Subscription|ResourceCredit|UsageLimit|EnterpriseSubscription/i.test(op)) { const input = unwrapInput(vars); const now = new Date().toISOString(); await env.CRM_DB.prepare("INSERT INTO workspace_billing (workspace_id, updated_at) VALUES (?, ?) ON CONFLICT(workspace_id) DO NOTHING").bind(workspaceId, now).run(); if (/SwitchBillingPlan|SetResourceCreditSubscriptionPrice|SwitchSubscriptionInterval/i.test(op)) { await env.CRM_DB.prepare("UPDATE workspace_billing SET plan = COALESCE(?, plan), billing_interval = COALESCE(?, billing_interval), updated_at = ? WHERE workspace_id = ?").bind(input.plan ? String(input.plan).slice(0, 40) : null, input.interval === "year" ? "year" : input.interval === "month" ? "month" : null, now, workspaceId).run(); } const row = await env.CRM_DB.prepare("SELECT plan, billing_interval as billingInterval, resource_credits as resourceCredits, credits_used as creditsUsed, status, updated_at as updatedAt FROM workspace_billing WHERE workspace_id = ?").bind(workspaceId).first(); return Response.json({ data: { enterpriseSubscriptionStatus: row, resourceCreditUsage: row, usageQuotasWithConsumption: row, switchBillingPlan: row, switchSubscriptionInterval: row, billingPortalSession: { url: null } } }); }
  if (/TimelineActivityTypes/i.test(op)) return Response.json({ data: { timelineActivityTypes: ["note", "task", "call", "email"].map((type) => ({ id: type, type, label: type[0].toUpperCase() + type.slice(1), isActive: true })) } });
  if (/TimelineCalendarEvents|TimelineThreads/i.test(op)) { const recordId = String(vars.objectRecordId ?? vars.recordId ?? vars.id ?? ""); const activities = await env.CRM_DB.prepare("SELECT id, type, title, body, due_at as dueAt, completed_at as completedAt, created_at as createdAt, updated_at as updatedAt FROM activities WHERE workspace_id = ? AND (contact_id = ? OR company_id = ? OR opportunity_id = ?) ORDER BY created_at DESC LIMIT 200").bind(workspaceId, recordId, recordId, recordId).all(); return Response.json({ data: { timelineCalendarEvents: activities.results, timelineThreads: activities.results, events: activities.results, threads: activities.results } }); }
  if (/UpdateWorkspace|ActivateWorkspace|RenameWorkspace/i.test(op)) { const input = unwrapInput(vars); const name = typeof input.name === "string" ? input.name.trim().slice(0, 120) : ""; if (name) await env.CRM_DB.prepare("UPDATE workspaces SET name = ? WHERE id = ?").bind(name, workspaceId).run(); const workspace = await env.CRM_DB.prepare("SELECT id, name, created_at as createdAt FROM workspaces WHERE id = ?").bind(workspaceId).first(); return Response.json({ data: { updateWorkspace: workspace, activateWorkspace: workspace, workspace } }); }
  if (/MaintenanceMode|PublicFeatureFlag|Dismiss.*Banner|ReconnectAccountBanner|LabPublicFeatureFlag/i.test(op)) { const input = unwrapInput(vars); const settingKey = /Maintenance/i.test(op) ? "maintenance" : /Reconnect/i.test(op) ? "reconnectBanner" : /Dismiss/i.test(op) ? "dismissedBanners" : "featureFlags"; const current = await env.CRM_DB.prepare("SELECT value_json as value FROM workspace_settings WHERE workspace_id = ? AND setting_key = ?").bind(workspaceId, settingKey).first<{ value: string }>(); let value: unknown = current ? JSON.parse(current.value) : {}; if (/Set|Update|Dismiss/i.test(op)) { value = { ...(typeof value === "object" && value ? value as Record<string, unknown> : {}), ...(input.flag ? { [String(input.flag)]: input.enabled !== false } : {}), ...(input.dismissed !== undefined ? { dismissed: input.dismissed } : {}), ...(input.enabled !== undefined && !input.flag ? { enabled: input.enabled } : {}) }; await env.CRM_DB.prepare("INSERT INTO workspace_settings (workspace_id, setting_key, value_json, updated_at, updated_by) VALUES (?, ?, ?, ?, ?) ON CONFLICT(workspace_id, setting_key) DO UPDATE SET value_json = excluded.value_json, updated_at = excluded.updated_at, updated_by = excluded.updated_by").bind(workspaceId, settingKey, JSON.stringify(value), new Date().toISOString(), actor.subject).run(); } return Response.json({ data: { maintenanceMode: value, isMaintenanceModeBannerDismissed: value, updateLabPublicFeatureFlag: value, dismissMaintenanceModeBanner: value } }); }
  if (/RunWorkflow|Trigger.*Workflow|Execute.*Workflow|SendEmail|StartChannelSync|RetryJobs/i.test(op)) { const runId = crypto.randomUUID(); const payload = { schemaVersion: 1 as const, id: runId, queueName: "twenty-jobs", jobName: op, data: { ...vars, workspaceId, actorSubject: actor.subject }, createdAt: new Date().toISOString(), retryLimit: 3, priority: 0 }; try { await env.JOBS_QUEUE.send(payload); } catch (error) { console.warn("workflow enqueue failed", { op, error: String(error) }); return Response.json({ errors: [{ message: "workflow enqueue failed" }] }, { status: 503 }); } return Response.json({ data: { runWorkflowVersion: { id: runId, status: "queued" }, runWorkflow: { id: runId, status: "queued" }, execute: { id: runId, status: "queued" }, sendEmail: { id: runId, status: "queued" } } }); }
  if (/GetRoles|Role/i.test(op) && !entityFor(op)) { const rows = await env.CRM_DB.prepare("SELECT identity_subject as id, identity_subject as name, role, status FROM workspace_members WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); return Response.json({ data: { roles: [{ id: "owner", label: "Owner" }, { id: "admin", label: "Admin" }, { id: "member", label: "Member" }], workspaceMembers: rows.results, members: rows.results } }); }
  if (/Invitation/i.test(op) && !entityFor(op)) {
    if (/GetWorkspaceInvitations|FindMany/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, email, role, status, expires_at as expiresAt, created_at as createdAt, accepted_at as acceptedAt FROM workspace_invitations WHERE workspace_id = ? ORDER BY created_at DESC LIMIT 200").bind(workspaceId).all(); return Response.json({ data: { workspaceInvitations: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length }, invitations: rows.results } }); }
    if (/SendInvitations|Create/i.test(op)) { const input = unwrapInput(vars); const emails = Array.isArray(input.emails) ? input.emails : [input.email]; const now = new Date(); const role = input.role === "admin" ? "admin" : "member"; const created = []; for (const raw of emails) { if (typeof raw !== "string" || !raw.includes("@")) continue; const id = crypto.randomUUID(); const tokenHash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(crypto.randomUUID())); const hash = [...new Uint8Array(tokenHash)].map((b) => b.toString(16).padStart(2, "0")).join(""); const expires = new Date(now.getTime() + 7 * 86400000).toISOString(); await env.CRM_DB.prepare("INSERT INTO workspace_invitations (id, workspace_id, email, role, token_hash, status, expires_at, created_at) VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)").bind(id, workspaceId, raw.toLowerCase(), role, hash, expires, now.toISOString()).run(); created.push({ id, email: raw.toLowerCase(), role, status: "pending", expiresAt: expires }); } return Response.json({ data: { sendInvitations: created, invitations: created } }); }
    if (/Delete|Revoke|Resend/i.test(op)) { const invitationId = String(vars.id ?? vars.invitationId ?? unwrapInput(vars).id ?? ""); if (invitationId) await env.CRM_DB.prepare("UPDATE workspace_invitations SET status = 'revoked' WHERE workspace_id = ? AND id = ?").bind(workspaceId, invitationId).run(); return Response.json({ data: { deleteWorkspaceInvitation: { id: invitationId }, resendWorkspaceInvitation: { id: invitationId } } }); }
  }
  if (/Metadata/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, object_key as name, label, plural_label as pluralLabel, created_at as createdAt, updated_at as updatedAt FROM custom_objects WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); const fields = await env.CRM_DB.prepare("SELECT id, object_type as objectType, field_key as name, label, field_type as type, options_json as options, created_at as createdAt FROM custom_fields WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); return Response.json({ data: { objectMetadataItems: rows.results, objects: rows.results, fieldMetadataItems: fields.results, fields: fields.results, minimalMetadata: { objects: rows.results, fields: fields.results } } }); }
  if (/View/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, object_type as objectType, name, filters_json as filters, sort_json as sort, created_at as createdAt, updated_at as updatedAt FROM saved_views WHERE workspace_id = ? ORDER BY updated_at DESC").bind(workspaceId).all(); return Response.json({ data: { views: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length }, findManyViews: rows.results } }); }
  if (/Relation/i.test(op) || vars.relationKey) {
    const input = unwrapInput(vars); const sourceType = String(vars.sourceType ?? input.sourceType ?? vars.objectName ?? ""); const sourceId = String(vars.sourceId ?? input.sourceId ?? vars.recordId ?? ""); const targetType = String(vars.targetType ?? input.targetType ?? ""); const targetId = String(vars.targetId ?? input.targetId ?? ""); const relationKey = String(vars.relationKey ?? input.relationKey ?? "related");
    if (/Create|Connect|Update|Add/i.test(op) && sourceId && targetId) { const now = new Date().toISOString(); await env.CRM_DB.prepare("INSERT OR IGNORE INTO record_relationships (id, workspace_id, source_type, source_id, target_type, target_id, relation_key, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(crypto.randomUUID(), workspaceId, sourceType, sourceId, targetType, targetId, relationKey, now).run(); }
    if (/Delete|Disconnect|Remove/i.test(op) && sourceId && targetId) await env.CRM_DB.prepare("DELETE FROM record_relationships WHERE workspace_id = ? AND source_type = ? AND source_id = ? AND target_type = ? AND target_id = ? AND relation_key = ?").bind(workspaceId, sourceType, sourceId, targetType, targetId, relationKey).run();
    const rows = await env.CRM_DB.prepare("SELECT id, source_type as sourceType, source_id as sourceId, target_type as targetType, target_id as targetId, relation_key as relationKey, created_at as createdAt FROM record_relationships WHERE workspace_id = ? AND ((source_type = ? AND source_id = ?) OR (target_type = ? AND target_id = ?)) ORDER BY created_at DESC LIMIT 200").bind(workspaceId, sourceType, sourceId, sourceType, sourceId).all(); return Response.json({ data: { recordRelations: rows.results, relations: rows.results, relation: rows.results[0] ?? null } });
  }
  if (/FileUpload|File/i.test(op) && !entityFor(op)) {
    const rows = await env.CRM_DB.prepare("SELECT id, filename, content_type as contentType, bytes, created_at as createdAt FROM crm_files WHERE workspace_id = ? ORDER BY created_at DESC LIMIT 100").bind(workspaceId).all();
    if (/Create|Complete/i.test(op)) { const input = unwrapInput(vars); const filename = String(input.filename ?? "upload.bin").slice(0, 255); const id = crypto.randomUUID(); return Response.json({ data: { createFileUpload: { id, filename, contentType: String(input.contentType ?? "application/octet-stream"), uploadUrl: `/api/crm/files`, signedUrl: `/api/crm/files` } } }); }
    return Response.json({ data: { files: { edges: rows.results.map((node) => ({ node })), nodes: rows.results, totalCount: rows.results.length }, fileUploads: rows.results } });
  }
  if (/FieldMetadata/i.test(op)) { const rows = await env.CRM_DB.prepare("SELECT id, object_type as objectType, field_key as name, label, field_type as type, options_json as options, created_at as createdAt FROM custom_fields WHERE workspace_id = ? ORDER BY created_at").bind(workspaceId).all(); return Response.json({ data: { fieldMetadataItems: rows.results, fields: rows.results } }); }
  if (/Search|CombinedFindManyRecords/i.test(op)) {
    const term = String(vars.searchTerm ?? vars.query ?? vars.q ?? "").slice(0, 120); const pattern = `%${term}%`;
    const [people, companies, opportunities] = await env.CRM_DB.batch([
      env.CRM_DB.prepare("SELECT id, first_name || ' ' || last_name AS name, email, 'person' AS objectType FROM contacts WHERE workspace_id = ? AND (first_name LIKE ? OR last_name LIKE ? OR email LIKE ?) LIMIT 25").bind(workspaceId, pattern, pattern, pattern),
      env.CRM_DB.prepare("SELECT id, name, domain, 'company' AS objectType FROM companies WHERE workspace_id = ? AND (name LIKE ? OR domain LIKE ?) LIMIT 25").bind(workspaceId, pattern, pattern),
      env.CRM_DB.prepare("SELECT id, name, stage, 'opportunity' AS objectType FROM opportunities WHERE workspace_id = ? AND (name LIKE ? OR stage LIKE ?) LIMIT 25").bind(workspaceId, pattern, pattern),
    ]); const results = people.results.concat(companies.results, opportunities.results); return Response.json({ data: { search: results, combinedFindManyRecords: results, records: results } });
  }
  const customKey = customObjectKey(vars);
  if (customKey) {
    const input = unwrapInput(vars); const id = String(vars.id ?? vars.recordId ?? input.id ?? "");
    if (/Delete|Destroy|Archive/i.test(op) && id) { await env.CRM_DB.prepare("DELETE FROM custom_records WHERE workspace_id = ? AND object_key = ? AND id = ?").bind(workspaceId, customKey, id).run(); return Response.json({ data: { deleteOne: { id } } }); }
    if (/Create|Update|Upsert|Merge/i.test(op)) { const recordId = id || crypto.randomUUID(); const now = new Date().toISOString(); const payload = { ...input }; delete payload.id; await env.CRM_DB.prepare("INSERT INTO custom_records (id, workspace_id, object_key, data_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET data_json = excluded.data_json, updated_at = excluded.updated_at").bind(recordId, workspaceId, customKey, JSON.stringify(payload), now, now).run(); return Response.json({ data: { [customKey]: { id: recordId, ...payload, createdAt: now, updatedAt: now } } }); }
    if (/FindOne|GetOne/i.test(op) || id) { const row = await env.CRM_DB.prepare("SELECT id, data_json, created_at as createdAt, updated_at as updatedAt FROM custom_records WHERE workspace_id = ? AND object_key = ? AND id = ?").bind(workspaceId, customKey, id).first<{ id: string; data_json: string; createdAt: string; updatedAt: string }>(); const data = row ? JSON.parse(row.data_json) as Record<string, unknown> : null; return Response.json({ data: { [customKey]: row ? { id: row.id, ...data, createdAt: row.createdAt, updatedAt: row.updatedAt } : null } }); }
    const limit = Math.min(100, Math.max(1, Number(vars.first ?? vars.limit ?? 25))); const offset = Math.max(0, Number(vars.offset ?? vars.skip ?? 0)); const rows = await env.CRM_DB.prepare("SELECT id, data_json, created_at as createdAt, updated_at as updatedAt FROM custom_records WHERE workspace_id = ? AND object_key = ? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(workspaceId, customKey, limit, offset).all<{ id: string; data_json: string; createdAt: string; updatedAt: string }>(); const nodes = rows.results.map((row) => ({ id: row.id, ...(JSON.parse(row.data_json) as Record<string, unknown>), createdAt: row.createdAt, updatedAt: row.updatedAt })); const connection = { edges: nodes.map((node) => ({ node, cursor: node.id })), nodes, pageInfo: { hasNextPage: nodes.length === limit, hasPreviousPage: offset > 0 }, totalCount: nodes.length }; return Response.json({ data: { [customKey]: connection, records: connection } });
  }
  if (/Aggregate|ObjectRecordCounts|Count/i.test(op)) {
    const entity = entityFor(op); const count = entity ? await env.CRM_DB.prepare(`SELECT COUNT(*) AS count FROM ${entity.table} WHERE workspace_id = ?`).bind(workspaceId).first<{ count: number }>() : null;
    return Response.json({ data: { aggregate: { count: Number(count?.count ?? 0) }, objectRecordCounts: count ? [{ objectName: entity?.plural, count: Number(count.count) }] : [] } });
  }
  if (/Workspace/i.test(op) && !entityFor(op)) { const workspace = await env.CRM_DB.prepare("SELECT id, name, created_at as createdAt FROM workspaces WHERE id = ?").bind(workspaceId).first(); return Response.json({ data: { workspace, currentWorkspace: workspace, workspaces: { edges: workspace ? [{ node: workspace }] : [], nodes: workspace ? [workspace] : [], totalCount: workspace ? 1 : 0 } } }); }
  const entity = entityFor(op) ?? entityFromVars(vars); if (!entity) { const root = rootField(body.query); return Response.json({ data: root ? { [root]: null } : {} }); }
  const input = unwrapInput(vars); const id = String(vars.id ?? vars.idToFind ?? vars.recordId ?? input.id ?? "");
  if (/Delete|Destroy|Archive/i.test(op)) { if (!id) return Response.json({ errors: [{ message: "id required" }] }, { status: 400 }); await env.CRM_DB.prepare(`DELETE FROM ${entity.table} WHERE workspace_id = ? AND id = ?`).bind(workspaceId, id).run(); return Response.json({ data: { [entity.singular]: { id }, [`delete${entity.singular[0].toUpperCase()}${entity.singular.slice(1)}`]: { id } } }); }
  if (/Create|Update|Upsert|Merge/i.test(op)) { const now = new Date().toISOString(); const recordId = id || crypto.randomUUID(); const fields = entity.columns.filter((column) => !["id", "created_at", "updated_at"].includes(column)).filter((column) => valueFor(input, column) !== undefined); if (/Create|Upsert/i.test(op) && !id) { const names = ["id", "workspace_id", ...fields, "created_at", "updated_at"]; const values = [recordId, workspaceId, ...fields.map((f) => valueFor(input, f)), now, now]; await env.CRM_DB.prepare(`INSERT INTO ${entity.table} (${names.join(",")}) VALUES (${names.map(() => "?").join(",")})`).bind(...values).run(); } else if (fields.length) await env.CRM_DB.prepare(`UPDATE ${entity.table} SET ${fields.map((f) => `${f} = ?`).join(",")}, updated_at = ? WHERE workspace_id = ? AND id = ?`).bind(...fields.map((f) => valueFor(input, f)), now, workspaceId, recordId).run(); const row = await env.CRM_DB.prepare(`SELECT * FROM ${entity.table} WHERE workspace_id = ? AND id = ?`).bind(workspaceId, recordId).first<Record<string, unknown>>(); return Response.json({ data: { [entity.singular]: row ? mapRow(row) : { id: recordId } } }); }
  const limit = Math.min(100, Math.max(1, Number(vars.first ?? vars.limit ?? 25))); const offset = Math.max(0, Number(vars.offset ?? vars.skip ?? 0)); const one = /^FindOne|^GetOne|^FindDuplicate/i.test(op) || (!!id && !/^FindMany|^GetMany|^FindAll/i.test(op));
  if (one) { const row = await env.CRM_DB.prepare(`SELECT * FROM ${entity.table} WHERE workspace_id = ? AND id = ?`).bind(workspaceId, id).first<Record<string, unknown>>(); return Response.json({ data: { [entity.singular]: row ? await enrich(env, workspaceId, entity, row) : null } }); }
  const rows = await env.CRM_DB.prepare(`SELECT * FROM ${entity.table} WHERE workspace_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(workspaceId, limit, offset).all<Record<string, unknown>>(); const nodes = await Promise.all(rows.results.map((row) => enrich(env, workspaceId, entity, row))); const connection = { edges: nodes.map((node) => ({ node, cursor: String(node.id ?? "") })), nodes, pageInfo: { hasNextPage: nodes.length === limit, hasPreviousPage: offset > 0, startCursor: nodes[0]?.id ?? null, endCursor: nodes.at(-1)?.id ?? null }, totalCount: nodes.length }; return Response.json({ data: { [entity.plural]: connection, ...(entity.plural === "people" ? { contacts: connection } : {}) } });
}
