import type { CloudflareTwentyJob, Env } from './types';
import { compatibilityId } from './compatibility-id';
import { handleRegisteredWebhookReceiver } from './webhook-receipt';

const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const hex=(bytes:ArrayBuffer)=>[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join('');

export function validateWebhookDestination(raw:string,env:Env):URL|null{
  let url:URL;try{url=new URL(raw);}catch{return null;}if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443'||url.hostname.endsWith('.local')||url.hostname==='localhost'||url.hostname==='0.0.0.0'||url.hostname==='[::1]'||/^(?:10|127|169\.254|192\.168)\./.test(url.hostname)||/^172\.(?:1[6-9]|2\d|3[01])\./.test(url.hostname))return null;
  const allowed=(env.WEBHOOK_ALLOWED_HOSTS??'').split(',').map(value=>value.trim().toLowerCase()).filter(Boolean);if(!allowed.length||!allowed.includes(url.hostname.toLowerCase()))return null;return url;
}

async function signature(secret:string,timestamp:string,body:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}:${body}`)));}

export async function enqueueOutboundWebhooks(env:Env,eventId:string,eventType:string,payload:Record<string,unknown>):Promise<void>{
  const workspaceId=typeof payload.workspaceId==='string'?payload.workspaceId:'';if(!workspaceId)return;if(!env.CRM_DB||!env.JOBS_QUEUE)throw new Error('outbound webhook persistence or queue is unavailable');
  const hooks=await env.CRM_DB.prepare("SELECT id,events_json as events FROM native_webhooks WHERE workspace_id=? AND active=1").bind(workspaceId).all<{id:string;events:string}>();const now=new Date().toISOString();
  for(const hook of hooks.results){let events:unknown=[];try{events=JSON.parse(hook.events);}catch{}if(Array.isArray(events)&&events.length&&!events.includes('*')&&!events.includes(eventType))continue;const deliveryId=await compatibilityId(`webhook-delivery:${hook.id}:${eventId}`);const inserted=await env.CRM_DB.prepare("INSERT OR IGNORE INTO webhook_deliveries (id,webhook_id,workspace_id,event_id,event_type,status,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,'queued',?,?,?)").bind(deliveryId,hook.id,workspaceId,eventId,eventType,JSON.stringify(payload),now,now).run();if(Number(inserted.meta?.changes??0)!==1)continue;const job:CloudflareTwentyJob={schemaVersion:1,id:deliveryId,queueName:'twenty-jobs',jobName:'webhook.deliver',data:{deliveryId,workspaceId},createdAt:now,retryLimit:8,priority:0,dedupeKey:`webhook:${deliveryId}`,retainDedupe:true};try{await env.JOBS_QUEUE.send(job);}catch(error){await env.CRM_DB.prepare("UPDATE webhook_deliveries SET status='failed',last_error=?,updated_at=? WHERE id=? AND workspace_id=?").bind(String(error).slice(0,500),new Date().toISOString(),deliveryId,workspaceId).run();throw error;}}
}

export async function executeWebhookDelivery(job:CloudflareTwentyJob,env:Env):Promise<Response>{
  const data=object(job.data),deliveryId=String(data.deliveryId??job.id),workspaceId=String(data.workspaceId??'');if(!deliveryId||!workspaceId)return new Response('invalid webhook job',{status:409});if(!env.OUTBOUND_WEBHOOK_SECRET)return new Response('outbound webhook secret unavailable',{status:503,headers:{'x-twenty-execution-outcome':'not-started'}});
  const row=await env.CRM_DB!.prepare("SELECT d.status,d.attempts,d.event_id as eventId,d.event_type as eventType,d.payload_json as payloadJson,w.url FROM webhook_deliveries d JOIN native_webhooks w ON w.id=d.webhook_id AND w.workspace_id=d.workspace_id WHERE d.id=? AND d.workspace_id=? AND w.active=1").bind(deliveryId,workspaceId).first<{status:string;attempts:number;eventId:string;eventType:string;payloadJson:string|null;url:string}>();if(!row)return new Response('webhook delivery not found',{status:409});if(row.status==='delivered'||row.status==='dead')return new Response(null,{status:204});const destination=validateWebhookDestination(row.url,env);if(!destination){await env.CRM_DB!.prepare("UPDATE webhook_deliveries SET status='dead',last_error='destination is not allowlisted',updated_at=? WHERE id=? AND workspace_id=?").bind(new Date().toISOString(),deliveryId,workspaceId).run();return new Response(null,{status:204});}
  let retainedPayload:Record<string,unknown>|null=null;try{const parsed=row.payloadJson?JSON.parse(row.payloadJson):null;if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))retainedPayload=parsed;}catch{}const fallback=object(data.payload);if(!retainedPayload&&!Object.keys(fallback).length){await env.CRM_DB!.prepare("UPDATE webhook_deliveries SET status='dead',last_error='original payload is unavailable',updated_at=? WHERE id=? AND workspace_id=?").bind(new Date().toISOString(),deliveryId,workspaceId).run();return new Response(null,{status:204});}const body=JSON.stringify({id:row.eventId,event:row.eventType,workspaceId,data:retainedPayload??fallback}),timestamp=String(Date.now());const signed=await signature(env.OUTBOUND_WEBHOOK_SECRET,timestamp,body);await env.CRM_DB!.prepare("UPDATE webhook_deliveries SET status='delivering',attempts=attempts+1,updated_at=? WHERE id=? AND workspace_id=?").bind(new Date().toISOString(),deliveryId,workspaceId).run();
  try{const headers={'content-type':'application/json','user-agent':'Twenty-Cloudflare-Webhook/1.0','x-twenty-webhook-id':row.eventId,'x-twenty-webhook-timestamp':timestamp,'x-twenty-webhook-signature':signed};const server=env.SERVER_URL?new URL(env.SERVER_URL):null;const isRegisteredLoopback=server&&destination.origin===server.origin&&destination.pathname==='/webhooks/receiver';const response=isRegisteredLoopback?await handleRegisteredWebhookReceiver(new Request(destination,{method:'POST',headers,body}),env):await fetch(destination,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(10_000),headers,body});const now=new Date().toISOString();if(response.ok){await env.CRM_DB!.prepare("UPDATE webhook_deliveries SET status='delivered',response_status=?,last_error=NULL,delivered_at=?,updated_at=? WHERE id=? AND workspace_id=?").bind(response.status,now,now,deliveryId,workspaceId).run();return new Response(null,{status:204});}const retry=response.status===408||response.status===425||response.status===429||response.status>=500;await env.CRM_DB!.prepare("UPDATE webhook_deliveries SET status=?,response_status=?,last_error=?,updated_at=? WHERE id=? AND workspace_id=?").bind(retry?'failed':'dead',response.status,`HTTP ${response.status}`,now,deliveryId,workspaceId).run();return retry?new Response('webhook transient failure',{status:503}):new Response(null,{status:204});}
  catch(error){await env.CRM_DB!.prepare("UPDATE webhook_deliveries SET status='failed',last_error=?,updated_at=? WHERE id=? AND workspace_id=?").bind(String(error).slice(0,500),new Date().toISOString(),deliveryId,workspaceId).run();return new Response('webhook delivery failed',{status:503});}
}
