import { compatibilityId } from './compatibility-id';
import { decryptProviderValue, encryptProviderValue } from './provider-crypto';
import type { CloudflareTwentyJob, Env } from './types';

type Provider='google'|'microsoft';
type Tokens={access_token:string;refresh_token?:string;expires_in?:number;expires_at?:string;scope?:string;token_type?:string};
type Credential={provider:Provider;encryptedTokens:string;tokenIv:string};
const object=(value:unknown):Record<string,any>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};
const timeout=()=>AbortSignal.timeout(15_000);
const tokenEndpoint=(provider:Provider,env:Env)=>provider==='google'?'https://oauth2.googleapis.com/token':`https://login.microsoftonline.com/${env.MICROSOFT_OAUTH_TENANT_ID||'common'}/oauth2/v2.0/token`;
const client=(provider:Provider,env:Env)=>provider==='google'?{id:env.GOOGLE_OAUTH_CLIENT_ID,secret:env.GOOGLE_OAUTH_CLIENT_SECRET}:{id:env.MICROSOFT_OAUTH_CLIENT_ID,secret:env.MICROSOFT_OAUTH_CLIENT_SECRET};

async function credential(env:Env,workspaceId:string,accountId:string):Promise<Credential|null>{return env.CRM_DB!.prepare("SELECT c.provider,c.encrypted_tokens as encryptedTokens,c.token_iv as tokenIv FROM integration_credentials c JOIN integration_accounts a ON a.id=c.account_id AND a.workspace_id=c.workspace_id WHERE c.account_id=? AND c.workspace_id=? AND a.status='connected'").bind(accountId,workspaceId).first<Credential>();}
async function saveTokens(env:Env,workspaceId:string,accountId:string,provider:Provider,tokens:Tokens){const encrypted=await encryptProviderValue(env,tokens,`integration:${workspaceId}:${accountId}:${provider}`);await env.CRM_DB!.prepare('UPDATE integration_credentials SET encrypted_tokens=?,token_iv=?,token_expires_at=?,refresh_claimed_at=NULL,updated_at=? WHERE account_id=? AND workspace_id=?').bind(encrypted.ciphertext,encrypted.iv,tokens.expires_at??null,new Date().toISOString(),accountId,workspaceId).run();}
async function refresh(env:Env,workspaceId:string,accountId:string,provider:Provider,tokens:Tokens):Promise<Tokens>{
  if(!tokens.refresh_token)throw new Error('refresh_token_missing');const providerClient=client(provider,env);if(!providerClient.id||!providerClient.secret)throw new Error('oauth_client_missing');
  const now=new Date(),stale=new Date(now.getTime()-2*60_000).toISOString();const claimed=await env.CRM_DB!.prepare('UPDATE integration_credentials SET refresh_claimed_at=? WHERE account_id=? AND workspace_id=? AND (refresh_claimed_at IS NULL OR refresh_claimed_at<?)').bind(now.toISOString(),accountId,workspaceId,stale).run();if(Number(claimed.meta?.changes??0)!==1)throw new Error('refresh_in_progress');
  try{const body=new URLSearchParams({client_id:providerClient.id,client_secret:providerClient.secret,grant_type:'refresh_token',refresh_token:tokens.refresh_token});if(provider==='microsoft')body.set('scope','openid email profile offline_access User.Read Calendars.Read Mail.Read');const response=await fetch(tokenEndpoint(provider,env),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body,signal:timeout()});const value=await response.json().catch(()=>({})) as Partial<Tokens>;if(!response.ok||typeof value.access_token!=='string')throw new Error(`refresh_http_${response.status}`);const updated:Tokens={...tokens,...value,access_token:value.access_token,refresh_token:value.refresh_token??tokens.refresh_token,expires_at:value.expires_in?new Date(Date.now()+Number(value.expires_in)*1000).toISOString():tokens.expires_at};await saveTokens(env,workspaceId,accountId,provider,updated);return updated;}catch(error){await env.CRM_DB!.prepare('UPDATE integration_credentials SET refresh_claimed_at=NULL,updated_at=? WHERE account_id=? AND workspace_id=?').bind(new Date().toISOString(),accountId,workspaceId).run();throw error;}
}
async function accessTokens(env:Env,workspaceId:string,accountId:string):Promise<{provider:Provider;tokens:Tokens}>{const row=await credential(env,workspaceId,accountId);if(!row)throw new Error('credential_not_found');let tokens=await decryptProviderValue<Tokens>(env,row.encryptedTokens,row.tokenIv,`integration:${workspaceId}:${accountId}:${row.provider}`);if(tokens.expires_at&&Date.parse(tokens.expires_at)<=Date.now()+120_000)tokens=await refresh(env,workspaceId,accountId,row.provider,tokens);return{provider:row.provider,tokens};}
async function providerFetch(url:string,token:string){const parsed=new URL(url);if(parsed.protocol!=='https:'||!['www.googleapis.com','graph.microsoft.com'].includes(parsed.hostname))throw new Error('provider_url_rejected');return fetch(parsed,{headers:{authorization:`Bearer ${token}`,accept:'application/json'},signal:timeout()});}
async function upsertFolder(env:Env,workspaceId:string,accountId:string,id:string,name:string,type:string|null){await env.CRM_DB!.prepare('INSERT INTO integration_message_folders (account_id,workspace_id,provider_folder_id,name,folder_type,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(account_id,provider_folder_id) DO UPDATE SET name=excluded.name,folder_type=excluded.folder_type,updated_at=excluded.updated_at').bind(accountId,workspaceId,id,name.slice(0,255),type?.slice(0,80)??null,new Date().toISOString()).run();}
async function upsertEvent(env:Env,workspaceId:string,accountId:string,provider:Provider,event:Record<string,any>){
  const providerId=String(event.id??'');if(!providerId)return;const id=await compatibilityId(`provider-event:${workspaceId}:${accountId}:${providerId}`);
  const googleStart=object(event.start),googleEnd=object(event.end),microsoftStart=object(event.start),microsoftEnd=object(event.end);
  const startsAt=provider==='google'?String(googleStart.dateTime??googleStart.date??''):String(microsoftStart.dateTime??'');if(!startsAt||Number.isNaN(Date.parse(startsAt)))return;
  const endsAt=provider==='google'?String(googleEnd.dateTime??googleEnd.date??''):String(microsoftEnd.dateTime??'');
  const title=String(provider==='google'?event.summary:event.subject??'Untitled event').slice(0,255),description=String(provider==='google'?event.description??'':object(event.bodyPreview).content??event.bodyPreview??'').slice(0,5000),location=String(provider==='google'?event.location??'':object(event.location).displayName??'').slice(0,500);
  const attendees=Array.isArray(event.attendees)?event.attendees:Array.isArray(event.attendees?.value)?event.attendees.value:[];const participants=attendees.slice(0,100).map((item:unknown)=>{const value=object(item);return{email:String(value.email??object(value.emailAddress).address??'').slice(0,254),name:String(value.displayName??object(value.emailAddress).name??'').slice(0,160)};}).filter((item:{email:string})=>item.email);
  const now=new Date().toISOString();await env.CRM_DB!.prepare("INSERT INTO native_calendar_events (id,workspace_id,title,description,starts_at,ends_at,all_day,location,participants_json,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,starts_at=excluded.starts_at,ends_at=excluded.ends_at,all_day=excluded.all_day,location=excluded.location,participants_json=excluded.participants_json,status=excluded.status,updated_at=excluded.updated_at").bind(id,workspaceId,title,description,startsAt,endsAt&&!Number.isNaN(Date.parse(endsAt))?endsAt:null,provider==='google'?Number(Boolean(googleStart.date)):Number(Boolean(event.isAllDay)),location||null,JSON.stringify(participants),String(event.status??'confirmed').slice(0,40),`integration:${accountId}`,now,now).run();
}
async function syncGoogle(env:Env,workspaceId:string,accountId:string,token:string){const labels=await providerFetch('https://www.googleapis.com/gmail/v1/users/me/labels',token);if(!labels.ok)throw new Error(`gmail_http_${labels.status}`);const labelBody=await labels.json() as any;for(const label of Array.isArray(labelBody.labels)?labelBody.labels:[])await upsertFolder(env,workspaceId,accountId,String(label.id),String(label.name??label.id),String(label.type??''));
  let pageToken:string|undefined;for(let page=0;page<10;page++){const url=new URL('https://www.googleapis.com/calendar/v3/calendars/primary/events');url.searchParams.set('singleEvents','true');url.searchParams.set('maxResults','250');url.searchParams.set('timeMin',new Date(Date.now()-30*24*60*60_000).toISOString());if(pageToken)url.searchParams.set('pageToken',pageToken);const response=await providerFetch(url.toString(),token);if(!response.ok)throw new Error(`google_calendar_http_${response.status}`);const body=await response.json() as any;for(const event of Array.isArray(body.items)?body.items:[])await upsertEvent(env,workspaceId,accountId,'google',event);pageToken=typeof body.nextPageToken==='string'?body.nextPageToken:undefined;if(!pageToken)break;}}
async function syncMicrosoft(env:Env,workspaceId:string,accountId:string,token:string){let folders='https://graph.microsoft.com/v1.0/me/mailFolders?$top=100';for(let page=0;folders&&page<10;page++){const response=await providerFetch(folders,token);if(!response.ok)throw new Error(`microsoft_mail_http_${response.status}`);const body=await response.json() as any;for(const folder of Array.isArray(body.value)?body.value:[])await upsertFolder(env,workspaceId,accountId,String(folder.id),String(folder.displayName??folder.id),null);folders=typeof body['@odata.nextLink']==='string'?body['@odata.nextLink']:'';}
  const start=new Date(Date.now()-30*24*60*60_000).toISOString(),end=new Date(Date.now()+365*24*60*60_000).toISOString();let events=`https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=${encodeURIComponent(start)}&endDateTime=${encodeURIComponent(end)}&$top=100`;for(let page=0;events&&page<10;page++){const response=await providerFetch(events,token);if(!response.ok)throw new Error(`microsoft_calendar_http_${response.status}`);const body=await response.json() as any;for(const event of Array.isArray(body.value)?body.value:[])await upsertEvent(env,workspaceId,accountId,'microsoft',event);events=typeof body['@odata.nextLink']==='string'?body['@odata.nextLink']:'';}}

export async function executeProviderSync(job:CloudflareTwentyJob,env:Env):Promise<Response>{const data=object(job.data),workspaceId=String(data.workspaceId??''),accountId=String(data.accountId??'');if(!workspaceId||!accountId)return new Response('invalid provider sync job',{status:409});const started=new Date().toISOString();await env.CRM_DB!.prepare('UPDATE integration_sync_state SET last_started_at=?,last_error_code=NULL,updated_at=? WHERE account_id=? AND workspace_id=?').bind(started,started,accountId,workspaceId).run();try{let{provider,tokens}=await accessTokens(env,workspaceId,accountId);let attempt=0;for(;;){try{if(provider==='google')await syncGoogle(env,workspaceId,accountId,tokens.access_token);else await syncMicrosoft(env,workspaceId,accountId,tokens.access_token);break;}catch(error){if(attempt++===0&&String(error).includes('_http_401')&&tokens.refresh_token){tokens=await refresh(env,workspaceId,accountId,provider,tokens);continue;}throw error;}}const completed=new Date().toISOString();await env.CRM_DB!.prepare('UPDATE integration_sync_state SET last_completed_at=?,last_error_code=NULL,updated_at=? WHERE account_id=? AND workspace_id=?').bind(completed,completed,accountId,workspaceId).run();return new Response(null,{status:204});}catch(error){const code=String(error instanceof Error?error.message:error).replace(/[^A-Za-z0-9_-]/g,'_').slice(0,120);await env.CRM_DB!.prepare('UPDATE integration_sync_state SET last_error_code=?,updated_at=? WHERE account_id=? AND workspace_id=?').bind(code,new Date().toISOString(),accountId,workspaceId).run();return new Response('provider synchronization failed',{status:503,headers:{'x-twenty-execution-outcome':'not-started'}});}}
